<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RefPermissaoConfigSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $insert = [
            [
                'permissao_id' => 1,
                'permite_subst_bln' => false,
                'permissao_pai_id' => null,
                'grupo_pai_id' => null,
                'grupo_id' => null,
                'ordem' => null,
            ],
            [
                'permissao_id' => 2,
                'permite_subst_bln' => false,
                'permissao_pai_id' => 1,
                'grupo_pai_id' => null,
                'grupo_id' => 1,
                'ordem' => null,
            ],
            [
                'permissao_id' => 3,
                'permite_subst_bln' => true,
                'permissao_pai_id' => 2,
                'grupo_pai_id' => null,
                'grupo_id' => 2,
                'ordem' => null,
            ],
            [
                'permissao_id' => 4,
                'permite_subst_bln' => true,
                'permissao_pai_id' => 3,
                'grupo_pai_id' => null,
                'grupo_id' => 3,
                'ordem' => null,
            ],
            [
                'permissao_id' => 5,
                'permite_subst_bln' => true,
                'permissao_pai_id' => 4,
                'grupo_pai_id' => null,
                'grupo_id' => 4,
                'ordem' => null,
            ],
            [
                'permissao_id' => 6,
                'permite_subst_bln' => false,
                'permissao_pai_id' => 5,
                'grupo_pai_id' => null,
                'grupo_id' => 5,
                'ordem' => null,
            ],


            // [
            //     'permissao_id' => 4,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 5,
            //     'ordem' => 3,
            // ],
            // [
            //     'permissao_id' => 5,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 5,
            //     'ordem' => 4,
            // ],
            // [
            //     'permissao_id' => 6,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 5,
            //     'ordem' => 5,
            // ],
            // [
            //     'permissao_id' => 7,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 5,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 8,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 5,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 9,
            //     'permite_subst_bln' => true,
            //     'permissao_pai_id' => 62,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 3,
            //     'ordem' => null,
            // ],
            // [
            //     'permissao_id' => 10,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 6,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 11,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 11,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 12,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 11,
            //     'ordem' => 3,
            // ],
            // [
            //     'permissao_id' => 13,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => null,
            //     'ordem' => null,
            // ],
            // [
            //     'permissao_id' => 14,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => null,
            //     'ordem' => null,
            // ],
            // [
            //     'permissao_id' => 15,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => null,
            //     'ordem' => null,
            // ],
            // [
            //     'permissao_id' => 16,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 12,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 17,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 12,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 18,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 12,
            //     'ordem' => 3,
            // ],
            // [
            //     'permissao_id' => 19,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 13,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 20,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 13,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 21,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 11,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 22,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 5,
            //     'ordem' => 6,
            // ],
            // [
            //     'permissao_id' => 23,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 6,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 24,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 7,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 25,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 7,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 26,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 7,
            //     'ordem' => 3,
            // ],
            // [
            //     'permissao_id' => 27,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 7,
            //     'ordem' => 4,
            // ],
            // [
            //     'permissao_id' => 28,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 8,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 29,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 8,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 30,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 8,
            //     'ordem' => 3,
            // ],
            // [
            //     'permissao_id' => 31,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 9,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 32,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 9,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 33,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 9,
            //     'ordem' => 3,
            // ],
            // [
            //     'permissao_id' => 34,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 10,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 35,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 10,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 36,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 10,
            //     'ordem' => 3,
            // ],
            // [
            //     'permissao_id' => 37,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 14,
            //     'ordem' => 4,
            // ],
            // [
            //     'permissao_id' => 38,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 14,
            //     'ordem' => 5,
            // ],
            // [
            //     'permissao_id' => 39,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 14,
            //     'ordem' => 6,
            // ],
            // [
            //     'permissao_id' => 40,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 14,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 41,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 14,
            //     'ordem' => 3,
            // ],
            // [
            //     'permissao_id' => 42,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 14,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 43,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 15,
            //     'ordem' => 5,
            // ],
            // [
            //     'permissao_id' => 44,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 15,
            //     'ordem' => 6,
            // ],
            // [
            //     'permissao_id' => 45,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 15,
            //     'ordem' => 7,
            // ],
            // [
            //     'permissao_id' => 46,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 15,
            //     'ordem' => 3,
            // ],
            // [
            //     'permissao_id' => 47,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 15,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 48,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 15,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 49,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 16,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 50,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 16,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 51,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 16,
            //     'ordem' => 3,
            // ],
            // [
            //     'permissao_id' => 52,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 15,
            //     'ordem' => 4,
            // ],
            // [
            //     'permissao_id' => 54,
            //     'permite_subst_bln' => true,
            //     'permissao_pai_id' => 53,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 3,
            //     'ordem' => null,
            // ],
            // [
            //     'permissao_id' => 55,
            //     'permite_subst_bln' => true,
            //     'permissao_pai_id' => 53,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 3,
            //     'ordem' => null,
            // ],
            // [
            //     'permissao_id' => 56,
            //     'permite_subst_bln' => true,
            //     'permissao_pai_id' => 53,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 3,
            //     'ordem' => null,
            // ],
            // [
            //     'permissao_id' => 57,
            //     'permite_subst_bln' => true,
            //     'permissao_pai_id' => 53,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 3,
            //     'ordem' => null,
            // ],
            // [
            //     'permissao_id' => 58,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 54,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 17,
            //     'ordem' => null,
            // ],
            // [
            //     'permissao_id' => 59,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 55,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 17,
            //     'ordem' => null,
            // ],
            // [
            //     'permissao_id' => 60,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 56,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 17,
            //     'ordem' => null,
            // ],
            // [
            //     'permissao_id' => 61,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 57,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 17,
            //     'ordem' => null,
            // ],
            // [
            //     'permissao_id' => 63,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => null,
            //     'grupo_pai_id' => 17,
            //     'grupo_id' => 18,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 64,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => null,
            //     'grupo_pai_id' => 17,
            //     'grupo_id' => 18,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 65,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => null,
            //     'grupo_pai_id' => 17,
            //     'grupo_id' => 18,
            //     'ordem' => 3,
            // ],
            // [
            //     'permissao_id' => 66,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => null,
            //     'grupo_pai_id' => 17,
            //     'grupo_id' => 18,
            //     'ordem' => 4,
            // ],
            // [
            //     'permissao_id' => 67,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => null,
            //     'grupo_pai_id' => 17,
            //     'grupo_id' => 18,
            //     'ordem' => 5,
            // ],
            // [
            //     'permissao_id' => 68,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => 17,
            //     'grupo_id' => 18,
            //     'ordem' => 6,
            // ],
            // [
            //     'permissao_id' => 69,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 19,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 70,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 19,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 71,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 20,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 72,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 20,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 73,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 20,
            //     'ordem' => 3,
            // ],
            // [
            //     'permissao_id' => 74,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 21,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 75,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 21,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 76,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 22,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 77,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 22,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 78,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 22,
            //     'ordem' => 3,
            // ],
            // [
            //     'permissao_id' => 79,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 23,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 80,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 23,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 81,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 23,
            //     'ordem' => 3,
            // ],
            // [
            //     'permissao_id' => 82,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 24,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 83,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 24,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 84,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 24,
            //     'ordem' => 3,
            // ],
            // [
            //     'permissao_id' => 85,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 25,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 86,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 25,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 87,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 25,
            //     'ordem' => 3,
            // ],
            // [
            //     'permissao_id' => 88,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 26,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 89,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 26,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 90,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 26,
            //     'ordem' => 3,
            // ],
            // [
            //     'permissao_id' => 91,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 27,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 92,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 27,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 93,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 27,
            //     'ordem' => 3,
            // ],
            // [
            //     'permissao_id' => 94,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 28,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 95,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 28,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 96,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 29,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 97,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 29,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 98,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 30,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 99,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 30,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 100,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 31,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 101,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 31,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 102,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 32,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 103,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 32,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 104,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 33,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 105,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 9,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 33,
            //     'ordem' => 2,
            // ],
            // [
            //     'permissao_id' => 106,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 34,
            //     'ordem' => 1,
            // ],
            // [
            //     'permissao_id' => 107,
            //     'permite_subst_bln' => false,
            //     'permissao_pai_id' => 3,
            //     'grupo_pai_id' => null,
            //     'grupo_id' => 34,
            //     'ordem' => 2,
            // ],
        ];

        DB::table('ref_permissao_config')->insert($insert);
    }
}
