version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "172.14.239.101:8080:80" # Mapeia a porta 8080 do host para a porta 80 do container
    volumes:
      - .:/var/www/html
    networks:
      - laravel

networks:
  laravel:
