DROP TRIGGER IF EXISTS nome_tabela_INSERT_BEFORE;

delimiter $
CREATE TRIGGER nome_tabela_INSERT_BEFORE
BEFORE INSERT ON nome_tabela
FOR EACH ROW

BEGIN
    IF NEW.IDESTADONASC IS NULL OR NEW.IDESTADONASC = 0 THEN
		SET NEW.IDESTADONASC = DEFAULT;
	END IF;
    IF NEW.CPF IS NULL OR NEW.CPF = '' THEN
		SET NEW.CPF = DEFAULT;
	END IF;

	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
 END $
DESC nome_tabela;