DROP TRIGGER IF EXISTS nome_tabela_INSERT_AFTER;

delimiter $
CREATE TRIGGER nome_tabela_INSERT_AFTER
AFTER INSERT ON nome_tabela
FOR EACH ROW

begin
     -- Insere a primeira situação
     INSERT INTO nome_tabelasituacao (IDMUDANCA, IDSITUACAO, IDCADASTRO, IPCADASTRO, DATACADASTRO) VALUES 
     (NEW.ID, NEW.IDSITUACAO, NEW.IDCADASTRO, NEW.IPCADASTRO, NEW.DATACADASTRO);
          
END; $
DESC nome_tabela;
