DROP TRIGGER IF EXISTS cadastros_mudancacela_INSERT_BEFORE;

delimiter $
CREATE TRIGGER cadastros_mudancacela_INSERT_BEFORE
BEFORE INSERT ON cadastros_mudancacela
FOR EACH ROW

begin
	DECLARE IDBoletim int;
    
    SET IDBoletim = (SELECT ID FROM chefia_boletim WHERE BOLETIMDODIA = TRUE ORDER BY ID DESC LIMIT 1);
    
    -- IF NEW.IDBOLETIMENTRADA IS NULL OR NEW.IDBOLETIMENTRADA = 0 THEN
		SET NEW.IDBOLETIMENTRADA = IDBoletim;
    -- END IF;

	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
    
  END; $
 
 DESC cadastros_mudancacela;