DROP TRIGGER IF EXISTS cadastros_vulgos_INSERT_BEFORE;

delimiter $
CREATE TRIGGER cadastros_vulgos_INSERT_BEFORE
BEFORE INSERT ON cadastros_vulgos
FOR EACH ROW

begin
	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
 END $
DESC cadastros_vulgos;