DROP TRIGGER IF EXISTS cadastros_mudancacela_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER cadastros_mudancacela_UPDATE_BEFORE
BEFORE UPDATE ON cadastros_mudancacela
FOR EACH ROW

begin
	/*DECLARE valorAntigo blob;
	DECLARE valorNovo blob;*/
	DECLARE IDBoletim int;
    
    SET IDBoletim = (SELECT ID FROM chefia_boletim WHERE BOLETIMDODIA = TRUE);
    
    -- IF NEW.IDBOLETIMSAIDA IS NULL THEN
		SET NEW.IDBOLETIMSAIDA = IDBoletim;
    -- END IF;
    
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
	END IF;

    /*IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;*/

	-- Salva os log de alterações
    -- DATAPRISAO
    /*IF NEW.DATAPRISAO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DATAPRISAO; END IF;
    IF OLD.DATAPRISAO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DATAPRISAO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO cadastros_mudancacela_log (IDMOVIMENTACAO, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DATAPRISAO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;*/
    
	-- SET NEW.DATAATUALIZACAO = NULL;
	-- SET NEW.IPATUALIZACAO = NULL;
	-- SET NEW.IDATUALIZACAO = NULL;
 END; $
 
DESC cadastros_mudancacela;
