DROP TRIGGER IF EXISTS cadastros_vulgos_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER cadastros_vulgos_UPDATE_BEFORE
BEFORE UPDATE ON cadastros_vulgos
FOR EACH ROW

begin
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;
 END $
desc cadastros_vulgos;