DROP TRIGGER IF EXISTS cadastros_INSERT_BEFORE;

delimiter $
CREATE TRIGGER cadastros_INSERT_BEFORE
BEFORE INSERT ON cadastros
FOR EACH ROW

begin
    IF NEW.IDCIDADENASC IS NULL OR NEW.IDCIDADENASC = 0 THEN
		SET NEW.IDCIDADENASC = DEFAULT;
	END IF;
    IF NEW.IDESTADONASC IS NULL OR NEW.IDESTADONASC = 0 THEN
		SET NEW.IDESTADONASC = DEFAULT;
	END IF;
    IF NEW.RG IS NULL OR NEW.RG = '' THEN
		SET NEW.RG = DEFAULT;
	END IF;
    IF NEW.CPF IS NULL OR NEW.CPF = '' THEN
		SET NEW.CPF = DEFAULT;
	END IF;
    IF NEW.OUTRODOC IS NULL OR NEW.OUTRODOC = '' THEN
		SET NEW.OUTRODOC = DEFAULT;
	END IF;
    IF NEW.PAI IS NULL OR NEW.PAI = '' THEN
		SET NEW.PAI = DEFAULT;
	END IF;
    IF NEW.MAE IS NULL OR NEW.MAE = '' THEN
		SET NEW.MAE = DEFAULT;
	END IF;

	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
 END $
DESC cadastros;