DROP TRIGGER IF EXISTS cadastros_condenacao_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER cadastros_condenacao_UPDATE_BEFORE
BEFORE UPDATE ON cadastros_condenacao
FOR EACH ROW

begin
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;

	-- Salva os log de alterações
    IF NEW.ANOS <> OLD.ANOS OR NEW.MESES <> OLD.MESES OR NEW.DIAS <> OLD.DIAS THEN
		INSERT INTO cadastros_condenacao_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.IDPRESO, 'PENA', concat(OLD.ANOS, ' anos, ', OLD.MESES, ' meses, ', OLD.DIAS, ' dias'), 
        concat(NEW.ANOS, ' anos, ', NEW.MESES, ' meses, ', NEW.DIAS, ' dias'), NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    SET NEW.DATAATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.IDATUALIZACAO = NULL;
 END $
