DROP TRIGGER IF EXISTS chefia_mudancacela_INSERT_BEFORE;

delimiter $
CREATE TRIGGER chefia_mudancacela_INSERT_BEFORE
BEFORE INSERT ON chefia_mudancacela
FOR EACH ROW

begin
	DECLARE IDBoletim int;
    
    SET IDBoletim = (SELECT ID FROM chefia_boletim WHERE BOLETIMDODIA = TRUE ORDER BY ID DESC LIMIT 1);
	SET NEW.IDBOLETIM = IDBoletim;

 	IF NEW.OBSERVACOES IS NULL OR NEW.OBSERVACOES = '' THEN
 		SET NEW.OBSERVACOES = DEFAULT;
 	END IF;
	
 	IF NEW.IDSITUACAO IS NULL OR NEW.IDSITUACAO = 0 THEN
 		SET NEW.IDSITUACAO = DEFAULT;
 	END IF;
	
 	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
 		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
 	END IF;
     
     -- Pega o ID da última cela que ele está
     SET NEW.IDCELAATUAL = (SELECT ID FROM cadastros_mudancacela WHERE IDPRESO = NEW.IDPRESO 
     AND RAIOALTERADO IS NULL AND IDATUALIZACAO IS NULL AND DATAATUALIZACAO IS NULL ORDER BY ID DESC LIMIT 1);
          
     IF NEW.RAIODESTINO IS NULL OR NEW.RAIODESTINO = 0 OR NEW.CELADESTINO IS NULL OR NEW.CELADESTINO = 0 THEN
		IF NEW.RAIODESTINO IS NULL OR NEW.RAIODESTINO = 0 THEN
			SET NEW.RAIODESTINO = DEFAULT;
		END IF;
		SET NEW.CELADESTINO = NULL;
		SET NEW.IDSITUACAO = 3;
	ELSEIF NEW.IDSITUACAO = 0 OR NEW.IDSITUACAO IS NULL THEN        
			SET NEW.IDSITUACAO = 4;
	 END IF;
     
	 IF NEW.IDSITUACAO = 3 AND NEW.RAIODESTINO IS NOT NULL AND NEW.CELADESTINO IS NOT NULL THEN        
		SET NEW.IDSITUACAO = 4;
	 END IF;
     
     #Caso seja inserido já com status de Realizado
	 -- Se a situação for 6 é porque foi realizado a alteração da cela, então se insere no histórico de mudanças de celas
    IF NEW.IDSITUACAO = 6 THEN
		IF NEW.RAIODESTINO NOT IN (2, 13, 14, 16) THEN
			UPDATE cadastros_mudancacela SET RAIOALTERADO = NEW.RAIODESTINO, CELAALTERADO = NEW.CELADESTINO, 
            IDATUALIZACAO = NEW.IDCADASTRO, IPATUALIZACAO = NEW.IPCADASTRO, DATAATUALIZACAO = NEW.DATACADASTRO WHERE ID = NEW.IDCELAATUAL;
			INSERT INTO cadastros_mudancacela (IDPRESO, RAIO, CELA, IDCADASTRO, IPCADASTRO, DATACADASTRO) VALUES
			(NEW.IDPRESO, NEW.RAIODESTINO, NEW.CELADESTINO, NEW.IDCADASTRO, NEW.IPCADASTRO, NEW.DATACADASTRO);
		END IF;
	END IF;
     
END; $

DESC chefia_mudancacela;