DROP TRIGGER IF EXISTS chefia_boletim_INSERT_BEFORE;

delimiter $
CREATE TRIGGER chefia_boletim_INSERT_BEFORE
before insert ON chefia_boletim
FOR EACH ROW

begin
	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
END; $
