DROP TRIGGER IF EXISTS chefia_atendimentos_INSERT_AFTER;

delimiter $
CREATE TRIGGER chefia_atendimentos_INSERT_AFTER
AFTER INSERT ON chefia_atendimentos
FOR EACH ROW

BEGIN
    #INSERIR A SITUAÇÃO
     INSERT INTO chefia_atendimentossituacao (IDREFERENCIA, IDSITUACAO, IDCADASTRO, IPCADASTRO, DATACADASTRO) VALUES 
     (NEW.ID, NEW.IDSITUACAO, NEW.IDCADASTRO, NEW.IPCADASTRO, NEW.DATACADASTRO);
         
 END $
DESC chefia_atendimentos;