DROP TRIGGER IF EXISTS chefia_boletim_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER chefia_boletim_UPDATE_BEFORE
BEFORE UPDATE ON chefia_boletim
FOR EACH ROW

BEGIN
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;
    
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
	-- Salva os log de alterações
    -- IDDIRETOR
    IF NEW.IDDIRETOR IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDDIRETOR; END IF;
    IF OLD.IDDIRETOR IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDDIRETOR; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO chefia_boletim_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDDIRETOR', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;

	SET NEW.IDATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.DATAATUALIZACAO = NULL;
END; $

DESC chefia_boletim;