DROP TRIGGER IF EXISTS chefia_atendimentos_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER chefia_atendimentos_UPDATE_BEFORE
BEFORE UPDATE ON chefia_atendimentos
FOR EACH ROW

BEGIN
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;
    
    IF NEW.IDBOLETIM IS NULL OR NEW.IDBOLETIM = '' OR NEW.IDBOLETIM = 0 THEN
		SET NEW.IDBOLETIM = DEFAULT;
	END IF;
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
    IF OLD.IDSITUACAO NOT IN (13, 17) THEN
		IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
			IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
				SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
			END IF;
			IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
				SET NEW.IPEXCLUSOREGISTRO = NULL;
			END IF;
		END IF;
	ELSE
		SET NEW.IDEXCLUSOREGISTRO = NULL;
		SET NEW.IPEXCLUSOREGISTRO = NULL;
		SET NEW.DATAEXCLUSOREGISTRO = NULL;
    END IF;
    
    -- SE NÃO ESTIVER CONCLUÍDO ENTÃO AINDA É POSSÍVEL ALTERAR A SITUAÇÃO DO PRESO
	IF OLD.IDSITUACAO <> 13 THEN
		#SE A SITUAÇÃO FOR A AGUARDANDO RESPOSTA E TEM DATA MARCADA, ENTÃO SE ALTERA PARA AGENDADADO
		IF NEW.IDSITUACAO = 10 AND (SELECT DATAATEND FROM chefia_atendimentos_requis WHERE ID = OLD.IDREQ) IS NOT NULL THEN
			SET NEW.IDSITUACAO = 11;
		END IF;

		-- O ID SITUAÇÃO SÓ PODE ESTAR ENTRE OS PERMITIDOS
		IF NEW.IDSITUACAO IN (SELECT IDSITUACAO FROM tab_situacaofiltro WHERE IDTIPO = 7) THEN
			-- Insere a alteração da situação
			INSERT INTO chefia_atendimentossituacao (IDREFERENCIA, IDSITUACAO, IDCADASTRO, IPCADASTRO, DATACADASTRO) VALUES 
			(OLD.ID, NEW.IDSITUACAO, NEW.IDATUALIZACAO, NEW.IPATUALIZACAO, NEW.DATAATUALIZACAO);
			
			#SE FOR ALTERADO PARA EM ATENDIMENTO, ENTÃO É INSERIDO O IDBOLETIM DO DIA
			IF NEW.IDSITUACAO = 17 THEN
				SET NEW.IDBOLETIM = (SELECT ID FROM chefia_boletim WHERE BOLETIMDODIA = TRUE ORDER BY ID DESC LIMIT 1);
			END IF;
            
			IF NEW.IDSITUACAO = 13 AND OLD.IDBOLETIM IS NULL THEN
				SET NEW.IDBOLETIM = (SELECT ID FROM chefia_boletim WHERE BOLETIMDODIA = TRUE ORDER BY ID DESC LIMIT 1);
			END IF;

		ELSE
			SET NEW.IDSITUACAO = OLD.IDSITUACAO;
		END IF;
	ELSE
		SET NEW.IDSITUACAO = OLD.IDSITUACAO;
	END IF;
    
    -- IDBOLETIM
    IF NEW.IDBOLETIM IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDBOLETIM; END IF;
    IF OLD.IDBOLETIM IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDBOLETIM; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO chefia_atendimentos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDBOLETIM', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;

    SET NEW.DATAATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.IDATUALIZACAO = NULL;
 END; $

DESC chefia_atendimentos;