DROP TRIGGER IF EXISTS chefia_proced_bate_piso_grade_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER chefia_proced_bate_piso_grade_UPDATE_BEFORE
BEFORE UPDATE ON chefia_proced_bate_piso_grade
FOR EACH ROW

BEGIN
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;
 END; $

DESC chefia_proced_bate_piso_grade;