DROP TRIGGER IF EXISTS chefia_atendimentosnomes_INSERT_BEFORE;

delimiter $
CREATE TRIGGER chefia_atendimentosnomes_INSERT_BEFORE
BEFORE INSERT ON chefia_atendimentosnomes
FOR EACH ROW

BEGIN
	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
 END $
DESC chefia_atendimentosnomes;