DROP TRIGGER IF EXISTS cimic_transferencias_INSERT_BEFORE;

delimiter $
CREATE TRIGGER cimic_transferencias_INSERT_BEFORE
BEFORE INSERT ON cimic_transferencias
FOR EACH ROW

BEGIN
    #Se for exclusão por remoção ou retorno, não haverá data de retorno
    IF NEW.IDTIPOMOV IN (4, 5) THEN
		SET NEW.DATARETORNO = DEFAULT;
	ELSE
		IF NEW.DATARETORNO IS NULL OR NEW.DATARETORNO = '' OR NEW.DATARETORNO = '0000-00-00' THEN
			SET NEW.DATARETORNO = DEFAULT;
		END IF;
    END IF;

	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
    
	-- O ID SITUAÇÃO SÓ PODE ESTAR ENTRE OS PERMITIDOS
    IF NEW.IDSITUACAO <> NULL THEN
		IF NEW.IDSITUACAO IN (SELECT IDSITUACAO FROM tab_situacaofiltro WHERE IDTIPO = 3) THEN
			SET NEW.IDSITUACAO = DEFAULT;
		END IF;
	END IF;
    
 END $
DESC cimic_transferencias;