DROP TRIGGER IF EXISTS cimic_exclusoes_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER cimic_exclusoes_UPDATE_BEFORE
BEFORE UPDATE ON cimic_exclusoes
FOR EACH ROW

BEGIN
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;
	DECLARE idMudanca int;
    
	IF NEW.IDBOLETIM IS NULL OR NEW.IDBOLETIM = ''  OR NEW.IDBOLETIM = 0 THEN
		SET NEW.IDBOLETIM = NULL;
	END IF;
    
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;

	-- O ID SITUAÇÃO SÓ PODE ESTAR ENTRE O ARRAY DESSE TIPO
    IF NEW.IDSITUACAO <> OLD.IDSITUACAO AND NEW.IDSITUACAO IN (SELECT IDSITUACAO FROM tab_situacaofiltro WHERE IDTIPO = 8) THEN
		-- Insere a alteração da situação
		INSERT INTO cimic_exclusoessituacao (IDREFERENCIA, IDSITUACAO, IDCADASTRO, IPCADASTRO, DATACADASTRO) VALUES 
		(OLD.ID, NEW.IDSITUACAO, NEW.IDATUALIZACAO, NEW.IPATUALIZACAO, NEW.DATAATUALIZACAO);
        
        #SE FOR ALTERADO COMO REALIZADO, ENTÃO É INSERIDO O IDBOLETIM DO DIA
        IF NEW.IDSITUACAO = 13 THEN
			SET NEW.IDBOLETIM = (SELECT ID FROM chefia_boletim WHERE BOLETIMDODIA = TRUE ORDER BY ID DESC LIMIT 1);
            SET NEW.DATASAIDA = CURRENT_TIMESTAMP;

            SET idMudanca = (SELECT MUD2.ID FROM cadastros_mudancacela MUD2 WHERE MUD2.IDPRESO = OLD.IDPRESO AND MUD2.IDEXCLUSOREGISTRO IS NULL ORDER BY MUD2.ID DESC LIMIT 1);
            #Encerra a cela do preso
            UPDATE cadastros_mudancacela  SET RAIOALTERADO = 13, CELAALTERADO = 0, 
			IDATUALIZACAO = NEW.IDATUALIZACAO, IPATUALIZACAO = NEW.IPATUALIZACAO, DATAATUALIZACAO = NEW.DATAATUALIZACAO
            WHERE ID = idMudanca;
            
            #EXCLUI O IDPRESO DO CADASTRO
            UPDATE cadastros SET IDPRESO = NULL, IDATUALIZACAO = NEW.IDATUALIZACAO, IPATUALIZACAO = NEW.IPATUALIZACAO, DATAATUALIZACAO = NEW.DATAATUALIZACAO WHERE IDPRESO = OLD.IDPRESO;
            
        END IF;
	ELSE
		SET NEW.IDSITUACAO = OLD.IDSITUACAO;
    END IF;

	-- Salva os log de alterações
    -- IDBOLETIM
    IF NEW.IDBOLETIM IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDBOLETIM; END IF;
    IF OLD.IDBOLETIM IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDBOLETIM; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO cimic_exclusoes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDBOLETIM', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDTIPOMOV
    IF NEW.DATASAIDA IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DATASAIDA; END IF;
    IF OLD.DATASAIDA IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DATASAIDA; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO cimic_exclusoes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DATASAIDA', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDMOTIVO
    IF NEW.IDMOTIVO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDMOTIVO; END IF;
    IF OLD.IDMOTIVO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDMOTIVO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO cimic_exclusoes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDMOTIVO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    SET NEW.DATAATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.IDATUALIZACAO = NULL;
 END; $

DESC cimic_exclusoes;