DROP TRIGGER IF EXISTS cimic_apresentacoes_INSERT_AFTER;

delimiter $
CREATE TRIGGER cimic_apresentacoes_INSERT_AFTER
AFTER INSERT ON cimic_apresentacoes
FOR EACH ROW

BEGIN
    #INSERIR A SITUAÇÃO
     INSERT INTO cimic_apresentacoessituacao (IDREFERENCIA, IDSITUACAO, IDCADASTRO, IPCADASTRO, DATACADASTRO) VALUES 
     (NEW.ID, NEW.IDSITUACAO, NEW.IDCADASTRO, NEW.IPCADASTRO, NEW.DATACADASTRO);
         
 END $
DESC cimic_apresentacoes;