DROP TRIGGER IF EXISTS cimic_transferencias_intermed_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER cimic_transferencias_intermed_UPDATE_BEFORE
BEFORE UPDATE ON cimic_transferencias_intermed
FOR EACH ROW

BEGIN
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;
	IF NEW.DATAINTERM IS NULL OR NEW.DATAINTERM = '' OR NEW.DATAINTERM = '0000-00-00' THEN
		SET NEW.DATAINTERM = NULL;
	END IF;
    
	IF NEW.COMENTARIO IS NULL OR NEW.COMENTARIO = '' THEN
		SET NEW.COMENTARIO = NULL;
	END IF;
    
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;

	-- Salva os log de alterações
    -- DESTINOFINAL
    IF NEW.DESTINOFINAL IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DESTINOFINAL; END IF;
    IF OLD.DESTINOFINAL IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DESTINOFINAL; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO cimic_transferencias_intermed_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DESTINOFINAL', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- DATAINTERM
    IF NEW.DATAINTERM IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DATAINTERM; END IF;
    IF OLD.DATAINTERM IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DATAINTERM; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO cimic_transferencias_intermed_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DATAINTERM', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- COMENTARIO
    IF NEW.COMENTARIO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.COMENTARIO; END IF;
    IF OLD.COMENTARIO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.COMENTARIO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO cimic_transferencias_intermed_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'COMENTARIO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    SET NEW.DATAATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.IDATUALIZACAO = NULL;
 END; $

DESC cimic_transferencias_intermed;