DROP TRIGGER IF EXISTS cimic_apresentacoes_internas_presos_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER cimic_apresentacoes_internas_presos_UPDATE_BEFORE
BEFORE UPDATE ON cimic_apresentacoes_internas_presos
FOR EACH ROW

BEGIN
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;
    
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;

	-- Salva os log de alterações
    -- HORAAPRES
    IF NEW.HORAAPRES IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.HORAAPRES; END IF;
    IF OLD.HORAAPRES IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.HORAAPRES; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO cimic_apresentacoes_internas_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'HORAAPRES', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDMOTIVOAPRES
    IF NEW.IDMOTIVOAPRES IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDMOTIVOAPRES; END IF;
    IF OLD.IDMOTIVOAPRES IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDMOTIVOAPRES; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO cimic_apresentacoes_internas_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDMOTIVOAPRES', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
	-- O ID SITUAÇÃO SÓ PODE ESTAR ENTRE O ARRAY DESSE TIPO
    IF NEW.IDSITUACAO <> OLD.IDSITUACAO AND NEW.IDSITUACAO IN (SELECT IDSITUACAO FROM tab_situacaofiltro WHERE IDTIPO = 5) THEN
		-- Insere a alteração da situação
		INSERT INTO cimic_apresentacoes_internas_presossituacao (IDREFERENCIA, IDSITUACAO, IDCADASTRO, IPCADASTRO, DATACADASTRO) VALUES 
		(OLD.ID, NEW.IDSITUACAO, NEW.IDATUALIZACAO, NEW.IPATUALIZACAO, NEW.DATAATUALIZACAO);
        
        #SE FOR ALTERADO COMO EM ATENDIMENTO, ENTÃO É INSERIDO O IDBOLETIMSAIDA DO DIA
        IF NEW.IDSITUACAO = 17 THEN
			SET NEW.REALIZADOSAIDA = TRUE;
			SET NEW.IDBOLETIM = (SELECT ID FROM chefia_boletim WHERE BOLETIMDODIA = TRUE ORDER BY ID DESC LIMIT 1);
        END IF;

        IF NEW.IDSITUACAO = 13 THEN
			SET NEW.REALIZADO = TRUE;
        END IF;
	ELSE
		SET NEW.IDSITUACAO = OLD.IDSITUACAO;
    END IF;
    
    -- REALIZADOSAIDA
    IF NEW.REALIZADOSAIDA IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.REALIZADOSAIDA; END IF;
    IF OLD.REALIZADOSAIDA IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.REALIZADOSAIDA; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO cimic_apresentacoes_internas_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'REALIZADOSAIDA', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- REALIZADO
    IF NEW.REALIZADO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.REALIZADO; END IF;
    IF OLD.REALIZADO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.REALIZADO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO cimic_apresentacoes_internas_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'REALIZADO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    SET NEW.DATAATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.IDATUALIZACAO = NULL;
 END; $

DESC cimic_apresentacoes_internas_presos;
