DROP TRIGGER IF EXISTS cimic_transferencias_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER cimic_transferencias_UPDATE_BEFORE
BEFORE UPDATE ON cimic_transferencias
FOR EACH ROW

BEGIN
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;
	DECLARE idMudanca int;
    
    IF NEW.IDTIPOMOV IN (4, 5) THEN
		SET NEW.DATARETORNO = DEFAULT;
	ELSE
		IF NEW.DATARETORNO IS NULL OR NEW.DATARETORNO = '' OR NEW.DATARETORNO = '0000-00-00' THEN
			SET NEW.DATARETORNO = DEFAULT;
		END IF;
    END IF;
    
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;

	-- Salva os log de alterações
    -- IDTIPOMOV
    IF NEW.IDTIPOMOV IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDTIPOMOV; END IF;
    IF OLD.IDTIPOMOV IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDTIPOMOV; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO cimic_transferencias_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDTIPOMOV', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDMOTIVOMOV
    IF NEW.IDMOTIVOMOV IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDMOTIVOMOV; END IF;
    IF OLD.IDMOTIVOMOV IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDMOTIVOMOV; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO cimic_transferencias_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDMOTIVOMOV', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- REALIZADOSAIDA
    IF NEW.REALIZADOSAIDA IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.REALIZADOSAIDA; END IF;
    IF OLD.REALIZADOSAIDA IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.REALIZADOSAIDA; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO cimic_transferencias_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'REALIZADOSAIDA', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- REALIZADORETORNO
    IF NEW.REALIZADORETORNO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.REALIZADORETORNO; END IF;
    IF OLD.REALIZADORETORNO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.REALIZADORETORNO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO cimic_transferencias_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'REALIZADORETORNO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- DATARETORNO
    IF NEW.DATARETORNO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DATARETORNO; END IF;
    IF OLD.DATARETORNO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DATARETORNO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO cimic_transferencias_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DATARETORNO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
	-- O ID SITUAÇÃO SÓ PODE ESTAR ENTRE O ARRAY DESSE TIPO
    IF NEW.IDSITUACAO <> OLD.IDSITUACAO AND NEW.IDSITUACAO IN (SELECT IDSITUACAO FROM tab_situacaofiltro WHERE IDTIPO = 3) THEN
		-- Insere a alteração da situação
		INSERT INTO cimic_transferenciassituacao (IDREFERENCIA, IDSITUACAO, IDCADASTRO, IPCADASTRO, DATACADASTRO) VALUES 
		(OLD.ID, NEW.IDSITUACAO, NEW.IDATUALIZACAO, NEW.IPATUALIZACAO, NEW.DATAATUALIZACAO);
        
        #SE FOR ALTERADO COMO REALIZADO, ENTÃO É INSERIDO O IDBOLETIMSAIDA DO DIA
        IF NEW.IDSITUACAO = 13 THEN
			SET NEW.REALIZADOSAIDA = TRUE;
			SET NEW.IDBOLETIMSAIDA = (SELECT ID FROM chefia_boletim WHERE BOLETIMDODIA = TRUE ORDER BY ID DESC LIMIT 1);
			SET NEW.DATAHORASAIDA = NEW.DATAATUALIZACAO;
            
            SET idMudanca = (SELECT MUD2.ID FROM cadastros_mudancacela MUD2 WHERE MUD2.IDPRESO = OLD.IDPRESO AND MUD2.IDEXCLUSOREGISTRO IS NULL ORDER BY MUD2.ID DESC LIMIT 1);
            #Encerra a cela do preso
            UPDATE cadastros_mudancacela  SET RAIOALTERADO = 15, CELAALTERADO = 0, 
			IDATUALIZACAO = NEW.IDATUALIZACAO, IPATUALIZACAO = NEW.IPATUALIZACAO, DATAATUALIZACAO = NEW.DATAATUALIZACAO
            WHERE ID = idMudanca;

            #EXCLUI O IDPRESO DO CADASTRO
            UPDATE cadastros SET IDPRESO = NULL, IDATUALIZACAO = NEW.IDATUALIZACAO, IPATUALIZACAO = NEW.IPATUALIZACAO, DATAATUALIZACAO = NEW.DATAATUALIZACAO WHERE IDPRESO = OLD.IDPRESO;
            
		END IF;
	ELSE
		SET NEW.IDSITUACAO = OLD.IDSITUACAO;
    END IF;

	-- IDBOLETIMSAIDA
    IF NEW.IDBOLETIMSAIDA IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDBOLETIMSAIDA; END IF;
    IF OLD.IDBOLETIMSAIDA IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDBOLETIMSAIDA; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO cimic_transferencias_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDBOLETIMSAIDA', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDBOLETIMRETORNO
    IF NEW.IDBOLETIMRETORNO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDBOLETIMRETORNO; END IF;
    IF OLD.IDBOLETIMRETORNO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDBOLETIMRETORNO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO cimic_transferencias_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDBOLETIMRETORNO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;

	#SE FOR ALTERADO COMO RETORNO, ENTÃO É INSERIDO O IDBOLETIMRETORNO DO DIA
	IF NEW.REALIZADORETORNO = TRUE THEN
		SET NEW.IDBOLETIMRETORNO = (SELECT ID FROM chefia_boletim WHERE BOLETIMDODIA = TRUE ORDER BY ID DESC LIMIT 1);
		SET NEW.DATAHORARETORNO = NEW.DATAATUALIZACAO;
	END IF;

    SET NEW.DATAATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.IDATUALIZACAO = NULL;
 END; $

DESC cimic_transferencias;