DROP TRIGGER IF EXISTS cimic_exclusoes_INSERT_BEFORE;

delimiter $
CREATE TRIGGER cimic_exclusoes_INSERT_BEFORE
BEFORE INSERT ON cimic_exclusoes
FOR EACH ROW

BEGIN
	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
    
	CALL PROCED_gera_numero_ordem_saida(date_format(NEW.DATASAIDA, '%Y'), 3, NEW.IDCADASTRO, NEW.IPCADASTRO, @intIDORDEM);
	SET NEW.IDORDEM = @intIDORDEM;
    SET @intIDORDEM = 0;

	-- O ID SITUAÇÃO SÓ PODE ESTAR ENTRE OS PERMITIDOS
	IF NEW.IDSITUACAO NOT IN (SELECT IDSITUACAO FROM tab_situacaofiltro WHERE IDTIPO = 8) THEN
		SET NEW.IDSITUACAO = DEFAULT;
    END IF;
	
 END $

DESC cimic_exclusoes;