DROP TRIGGER IF EXISTS cimic_transferencias_INSERT_AFTER;

delimiter $
CREATE TRIGGER cimic_transferencias_INSERT_AFTER
AFTER INSERT ON cimic_transferencias
FOR EACH ROW

BEGIN
    #INSERIR A SITUAÇÃO
     INSERT INTO cimic_transferenciassituacao (IDREFERENCIA, IDSITUACAO, IDCADASTRO, IPCADASTRO, DATACADASTRO) VALUES 
     (NEW.ID, NEW.IDSITUACAO, NEW.IDCADASTRO, NEW.IPCADASTRO, NEW.DATACADASTRO);
         
 END $
DESC cimic_transferencias;