DROP table chefia_contagem;
create table chefia_contagem (
ID INT auto_increment,
IDBOLETIM INT NOT NULL,
TIPOCONTAGEM varchar(10) NOT NULL,
CELA varchar(2) NOT NULL,
A INT NOT NULL default 0,
B INT NOT NULL default 0,
C INT NOT NULL default 0,
D INT NOT NULL default 0,
MOD_E INT NOT NULL default 0,
ENF INT NOT NULL default 0,
TRI INT NOT NULL default 0,
RCD INT NOT NULL default 0,
PARL INT NOT NULL default 0,
INCL INT NOT NULL default 0,
MSP INT NOT NULL default 0,
TRAB INT NOT NULL default 0,
HOSP INT NOT NULL default 0,
primary key (ID),
foreign key (IDBOLETIM) references chefia_boletim(ID)) default char set utf8;

truncate chefia_contagem;
insert INTO chefia_contagem (IDBOLETIM, TIPOCONTAGEM, CELA) VALUES
(1,'INICIAL','01'),(1,'INICIAL','02'),(1,'INICIAL','03'),(1,'INICIAL','04'),(1,'INICIAL','05'),(1,'INICIAL','06'),(1,'INICIAL','07'),(1,'INICIAL','08'),(1,'INICIAL','09'),
(1,'INICIAL',10),(1,'INICIAL',11),(1,'INICIAL',12),(1,'INICIAL',13),(1,'INICIAL',14),(1,'INICIAL',15),(1,'INICIAL',16),
(1,'ALTERACOES','01'),(1,'ALTERACOES','02'),(1,'ALTERACOES','03'),(1,'ALTERACOES','04'),(1,'ALTERACOES','05'),(1,'ALTERACOES','06'),(1,'ALTERACOES','07'),(1,'ALTERACOES','08'),
(1,'ALTERACOES','09'),(1,'ALTERACOES',10),(1,'ALTERACOES',11),(1,'ALTERACOES',12),(1,'ALTERACOES',13),(1,'ALTERACOES',14),(1,'ALTERACOES',15),(1,'ALTERACOES',16)
;

-- Comandos para copiar a contagem anterior
INSERT INTO chefia_contagem (IDBOLETIM,TIPOCONTAGEM,CELA,A,B,C,D,E,ENF,TRI,RCD,PARL,INCL,MSP,TRAB,HOSP)
SELECT 14,'INICIAL',CINI.CELA, CINI.A + CALT.A, CINI.B + CALT.B, CINI.C + CALT.C, CINI.D + CALT.D, CINI.E + CALT.E, 
CINI.ENF + CALT.ENF, CINI.TRI + CALT.TRI, CINI.RCD + CALT.RCD, CINI.PARL + CALT.PARL, CINI.INCL + CALT.INCL, CINI.MSP + CALT.MSP, 
CINI.TRAB + CALT.TRAB, CINI.HOSP + CALT.HOSP FROM chefia_contagem CINI
INNER JOIN chefia_contagem CALT ON CINI.CELA = CALT.CELA
WHERE CINI.IDBOLETIM = 1 AND CALT.IDBOLETIM = 1 AND CINI.TIPOCONTAGEM = 'INICIAL' AND CALT.TIPOCONTAGEM = 'ALTERACOES';

INSERT INTO chefia_contagem (IDBOLETIM,TIPOCONTAGEM,CELA)
SELECT 14,'ALTERACOES',CELA FROM chefia_contagem WHERE IDBOLETIM = 1 AND TIPOCONTAGEM = 'ALTERACOES';

SELECT DISTINCT CONT.IDBOLETIM ID, concat(date_format(BI.DATABOLETIM, '%d/%m/%y'), ' - ',
CASE TU.PERIODODIURNO
WHEN TRUE THEN 'Diurno'
WHEN FALSE THEN 'Noturno' END) NOME
FROM chefia_contagem CONT
INNER JOIN chefia_boletim BI ON BI.ID = CONT.IDBOLETIM
INNER JOIN chefia_turnos TU ON BI.TURNO = TU.NOME
ORDER BY BI.DATABOLETIM DESC;

select * FROM chefia_boletim;
SELECT * FROM chefia_raioscelas;
SELECT * FROM chefia_contagem WHERE IDBOLETIM = 23 AND TIPOCONTAGEM = 'INICIAL' ORDER BY CELA;



