DROP TRIGGER IF EXISTS enf_medic_assistido_entregue_INSERT_BEFORE;

delimiter $
CREATE TRIGGER enf_medic_assistido_entregue_INSERT_BEFORE
BEFORE INSERT ON enf_medic_assistido_entregue
FOR EACH ROW

BEGIN
	IF NEW.DATAENTREGUE IS NULL OR NEW.DATAENTREGUE = '' OR NEW.DATAENTREGUE = '0000-00-00 00:00:00' THEN
		SET NEW.DATAENTREGUE = CURRENT_TIMESTAMP;
	END IF;

	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
    
    SET NEW.IDPERIODOENTREGUE = (SELECT IDPERIODOENTREGA FROM enf_medic_assistido WHERE ID = NEW.IDASS);
 END $
DESC enf_medic_assistido_entregue;