DROP TRIGGER IF EXISTS enf_medic_assistido_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER enf_medic_assistido_UPDATE_BEFORE
BEFORE UPDATE ON enf_medic_assistido
FOR EACH ROW

BEGIN
	DECLARE intIDUltimo INT;
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;
    
	SET intIDUltimo = (SELECT max(ID) FROM enf_medic_assistido_entregue WHERE IDASS = OLD.ID AND IDEXCLUSOREGISTRO IS NULL);
	IF intIDUltimo IS NOT NULL THEN
		#Caso a Data início for alterada para uma data maior que a data da primeira entrega
		IF date_format(NEW.DATAINICIO,'%Y-%m-%d') <> date_format(OLD.DATAINICIO,'%Y-%m-%d') THEN
			SET valorNovo = (SELECT DATAENTREGUE FROM enf_medic_assistido_entregue WHERE ID = intIDUltimo);
			IF date_format(NEW.DATAINICIO,'%Y-%m-%d') > date_format(valorNovo,'%Y-%m-%d') THEN
				SET NEW.DATAINICIO = valorNovo;
            END IF;
        END IF;
    END IF;

	IF NEW.DATATERMINO IS NULL OR NEW.DATATERMINO = '' OR NEW.DATATERMINO = '0000-00-00 00:00:00' THEN
		SET NEW.DATATERMINO = DEFAULT;
	END IF;
	
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF intIDUltimo IS NULL THEN
			IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
				SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
			END IF;
			IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
				SET NEW.IPEXCLUSOREGISTRO = NULL;
			END IF;
        ELSE
			SET NEW.IDATUALIZACAO = NEW.IDEXCLUSOREGISTRO;
            SET NEW.DATATERMINO = (SELECT DATAENTREGUE FROM enf_medic_assistido_entregue WHERE ID = intIDUltimo);
            
            SET NEW.IDEXCLUSOREGISTRO = NULL;
            SET NEW.IPEXCLUSOREGISTRO = NULL;
            SET NEW.DATAEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;

	-- Salva os log de alterações  
    -- QTDENTREGA
    IF NEW.QTDENTREGA IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.QTDENTREGA; END IF;
    IF OLD.QTDENTREGA IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.QTDENTREGA; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO enf_medic_assistido_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'QTDENTREGA', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDPERIODOENTREGA
    IF NEW.IDPERIODOENTREGA IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDPERIODOENTREGA; END IF;
    IF OLD.IDPERIODOENTREGA IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDPERIODOENTREGA; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO enf_medic_assistido_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDPERIODOENTREGA', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- DATAINICIO
    IF NEW.DATAINICIO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DATAINICIO; END IF;
    IF OLD.DATAINICIO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DATAINICIO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO enf_medic_assistido_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DATAINICIO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- DATATERMINO
    IF NEW.DATATERMINO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DATATERMINO; END IF;
    IF OLD.DATATERMINO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DATATERMINO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO enf_medic_assistido_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DATATERMINO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    SET NEW.DATAATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.IDATUALIZACAO = NULL;
 END; $

DESC enf_medic_assistido;