DROP TRIGGER IF EXISTS enf_atendimentosnomes_INSERT_BEFORE;

delimiter $
CREATE TRIGGER enf_atendimentosnomes_INSERT_BEFORE
BEFORE INSERT ON enf_atendimentosnomes
FOR EACH ROW

BEGIN
	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
 END $
DESC enf_atendimentosnomes;