DROP TRIGGER IF EXISTS enf_atendimentos_medic_INSERT_BEFORE;

delimiter $
CREATE TRIGGER enf_atendimentos_medic_INSERT_BEFORE
BEFORE INSERT ON enf_atendimentos_medic
FOR EACH ROW

BEGIN
    IF NEW.QTD IS NULL OR NEW.QTD = 0 THEN
		SET NEW.QTD = NULL;
	END IF;
    IF NEW.OBSERVACOES IS NULL OR NEW.OBSERVACOES = '' THEN
		SET NEW.OBSERVACOES = DEFAULT;
	END IF;

	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
 END $
DESC enf_atendimentos_medic;