DROP TRIGGER IF EXISTS enf_medic_entregues_INSERT_BEFORE;

delimiter $
CREATE TRIGGER enf_medic_entregues_INSERT_BEFORE
BEFORE INSERT ON enf_medic_entregues
FOR EACH ROW

BEGIN
	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
 END $
DESC enf_medic_entregues;