DROP TRIGGER IF EXISTS enf_medicamentos_INSERT_BEFORE;

delimiter $
CREATE TRIGGER enf_medicamentos_INSERT_BEFORE
BEFORE INSERT ON enf_medicamentos
FOR EACH ROW

BEGIN
    IF NEW.QTD IS NULL OR NEW.QTD = '' THEN
		SET NEW.QTD = 0;
	END IF;
    IF NEW.QTDESTOQUE IS NULL OR NEW.QTDESTOQUE = '' THEN
		SET NEW.QTDESTOQUE = 0;
	END IF;
    IF NEW.MINIMOESTOQUE IS NULL OR NEW.MINIMOESTOQUE = '' THEN
		SET NEW.MINIMOESTOQUE = 0;
	END IF;

	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
 END $
DESC enf_medicamentos;