
DROP TRIGGER IF EXISTS enf_atendimentos_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER enf_atendimentos_UPDATE_BEFORE
BEFORE UPDATE ON enf_atendimentos
FOR EACH ROW

begin
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;
	
 	IF NEW.DESCPEDIDO IS NULL OR NEW.DESCPEDIDO = '' THEN
 		SET NEW.DESCPEDIDO = NULL;
 	END IF;
    
    IF NEW.DESCATEND IS NULL OR NEW.DESCATEND = '' THEN
		SET NEW.DESCATEND = DEFAULT;
	END IF;

    IF NEW.HORAATEND IS NULL OR NEW.HORAATEND = '' THEN
		SET NEW.HORAATEND = DEFAULT;
	END IF;

    IF NEW.OBSERVACOES IS NULL OR NEW.OBSERVACOES = '' THEN
		SET NEW.OBSERVACOES = DEFAULT;
	END IF;
    
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;
    
	-- Salva os log de alterações
    -- IDTIPOATEND
    IF NEW.IDTIPOATEND IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDTIPOATEND; END IF;
    IF OLD.IDTIPOATEND IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDTIPOATEND; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO enf_atendimentos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDTIPOATEND', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- DESCPEDIDO
    IF NEW.DESCPEDIDO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DESCPEDIDO; END IF;
    IF OLD.DESCPEDIDO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DESCPEDIDO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO enf_atendimentos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DESCPEDIDO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- DESCATEND
    IF NEW.DESCATEND IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DESCATEND; END IF;
    IF OLD.DESCATEND IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DESCATEND; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO enf_atendimentos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DESCATEND', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- OBSERVACOES
    IF NEW.OBSERVACOES IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.OBSERVACOES; END IF;
    IF OLD.OBSERVACOES IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.OBSERVACOES; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO enf_atendimentos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'OBSERVACOES', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- DATASOLICITACAO
    IF NEW.DATASOLICITACAO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DATASOLICITACAO; END IF;
    IF OLD.DATASOLICITACAO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DATASOLICITACAO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO enf_atendimentos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DATASOLICITACAO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    IF NEW.IDEXCLUSOREGISTRO IS NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.HORAATEND IS NULL THEN
			SET NEW.IDSITUACAO = 10;
		ELSEIF NEW.HORAATEND IS NOT NULL AND NEW.IDSITUACAO IN (10, 11) THEN
			SET NEW.IDSITUACAO = 11;
		END IF;
		
	
		-- IDSITUACAO
		-- O ID SITUAÇÃO SÓ PODE ESTAR ENTRE O ARRAY DESSE TIPO
		IF NEW.IDSITUACAO <> OLD.IDSITUACAO AND NEW.IDSITUACAO IN (SELECT IDSITUACAO FROM tab_situacaofiltro WHERE IDTIPO = 6) THEN
			-- Insere a alteração da situação
			INSERT INTO enf_atendimentossituacao (IDREFERENCIA, IDSITUACAO, IDCADASTRO, IPCADASTRO, DATACADASTRO) VALUES 
			(OLD.ID, NEW.IDSITUACAO, NEW.IDATUALIZACAO, NEW.IPATUALIZACAO, NEW.DATAATUALIZACAO);
			
			#SE FOR ATUALIZADO COMO SAIU PARA O ATENDIMENTO, ENTÃO É INSERIDO O IDBOLETIM DO DIA
			IF NEW.IDSITUACAO = 17 THEN
				SET NEW.IDBOLETIM = (SELECT ID FROM chefia_boletim WHERE BOLETIMDODIA = TRUE ORDER BY ID DESC LIMIT 1);
			END IF;
			IF NEW.IDSITUACAO = 13 AND OLD.IDBOLETIM IS NULL THEN
				SET NEW.IDBOLETIM = (SELECT ID FROM chefia_boletim WHERE BOLETIMDODIA = TRUE ORDER BY ID DESC LIMIT 1);
			END IF;

		ELSE
			SET NEW.IDSITUACAO = OLD.IDSITUACAO;
		END IF;
	END IF;
	
	-- HORAATEND
    IF NEW.HORAATEND IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.HORAATEND; END IF;
    IF OLD.HORAATEND IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.HORAATEND; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO enf_atendimentos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'HORAATEND', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
	-- IDBOLETIM
    IF NEW.IDBOLETIM IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDBOLETIM; END IF;
    IF OLD.IDBOLETIM IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDBOLETIM; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO enf_atendimentos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDBOLETIM', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
	SET NEW.DATAATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.IDATUALIZACAO = NULL;
 END $

DESC enf_atendimentos;
DESC enf_atendimentos_log;