DROP TRIGGER IF EXISTS enf_atendimentos_INSERT_BEFORE;

delimiter $
CREATE TRIGGER enf_atendimentos_INSERT_BEFORE
BEFORE INSERT ON enf_atendimentos
FOR EACH ROW

begin
 	IF NEW.DESCPEDIDO IS NULL OR NEW.DESCPEDIDO = '' THEN
 		SET NEW.DESCPEDIDO = NULL;
 	END IF;
    
 	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
 		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
 	END IF;
    
    IF NEW.HORAATEND IS NULL THEN
		IF NEW.DATASOLICITACAO IS NULL OR NEW.DATASOLICITACAO = '' OR NEW.DATASOLICITACAO = '0000-00-00 00:00:00' THEN
			SET NEW.DATASOLICITACAO = CURRENT_TIMESTAMP;
		END IF;
 	END IF;
    
	#SE A SITUAÇÃO FOR A AGUARDANDO RESPOSTA E TEM DATA MARCADA, ENTÃO SE ALTERA PARA AGENDADADO
    IF NEW.IDSITUACAO = 10 AND (SELECT DATAATEND FROM enf_atendimentos_requis WHERE ID = NEW.IDREQ) IS NOT NULL THEN
		SET NEW.IDSITUACAO = 11;
    END IF;
         
	IF NEW.IDSITUACAO = 17 OR NEW.IDSITUACAO = 13 THEN
		SET NEW.IDBOLETIM = (SELECT ID FROM chefia_boletim WHERE BOLETIMDODIA = TRUE ORDER BY ID DESC LIMIT 1);
	END IF;

END; $

DESC enf_atendimentos;
