DROP TRIGGER IF EXISTS enf_atendimentos_requis_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER enf_atendimentos_requis_UPDATE_BEFORE
BEFORE UPDATE ON enf_atendimentos_requis
FOR EACH ROW

BEGIN
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;
    
    IF NEW.REQUISITANTE IS NULL OR NEW.REQUISITANTE = '' THEN
		SET NEW.REQUISITANTE = DEFAULT;
	END IF;
    
	IF NEW.DATAATEND IS NULL OR NEW.DATAATEND = '' THEN
		SET NEW.DATAATEND = DEFAULT;
    END IF;
    
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
	IF 13 NOT IN (SELECT IDSITUACAO FROM chefia_atendimentos WHERE IDREQ = OLD.ID) 
    AND 17 NOT IN (SELECT IDSITUACAO FROM chefia_atendimentos WHERE IDREQ = OLD.ID) THEN
		IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
			IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
				SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
			END IF;
			IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
				SET NEW.IPEXCLUSOREGISTRO = NULL;
			END IF;
		END IF;

		-- Salva os log de alterações
		-- IDTIPOATEND
		IF NEW.IDTIPOATEND IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDTIPOATEND; END IF;
		IF OLD.IDTIPOATEND IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDTIPOATEND; END IF;
		IF valorAntigo <> valorNovo THEN
			INSERT INTO enf_atendimentos_requis_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
			VALUES (OLD.ID, 'IDTIPOATEND', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
		END IF;
				
		-- REQUISITANTE
		IF NEW.REQUISITANTE IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.REQUISITANTE; END IF;
		IF OLD.REQUISITANTE IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.REQUISITANTE; END IF;
		IF valorAntigo <> valorNovo THEN
			INSERT INTO enf_atendimentos_requis_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
			VALUES (OLD.ID, 'REQUISITANTE', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
			
			IF NEW.REQUISITANTE IS NULL OR NEW.REQUISITANTE = '' THEN
				SET NEW.REQUISITANTE = DEFAULT;
			ELSE
				CALL PROCED_verificasugestao(NEW.REQUISITANTE,2,NEW.IDCADASTRO,NEW.IPCADASTRO);
			END IF;
		END IF;
				
		-- DATAATEND
		IF NEW.DATAATEND IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DATAATEND; END IF;
		IF OLD.DATAATEND IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DATAATEND; END IF;
		IF valorAntigo <> valorNovo THEN
			INSERT INTO enf_atendimentos_requis_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
			VALUES (OLD.ID, 'DATAATEND', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
		END IF;
	ELSE
		SET NEW.IDTIPOATEND = OLD.IDTIPOATEND;
		SET NEW.REQUISITANTE = OLD.REQUISITANTE;
		SET NEW.DATAATEND = OLD.DATAATEND;
		SET NEW.IDEXCLUSOREGISTRO = NULL;
		SET NEW.IPEXCLUSOREGISTRO = NULL;
		SET NEW.DATAEXCLUSOREGISTRO = NULL;
	END IF;
        	
    SET NEW.DATAATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.IDATUALIZACAO = NULL;
 END; $

DESC enf_atendimentos_requis;