DROP TRIGGER IF EXISTS entradas_presos_UPDATE_AFTER;

delimiter $
CREATE TRIGGER entradas_presos_UPDATE_AFTER
AFTER UPDATE ON entradas_presos
FOR EACH ROW

begin
	DECLARE presosExistentes int;
	SET presosExistentes = (SELECT COUNT(ID) FROM entradas_presos WHERE IDENTRADA = OLD.IDENTRADA AND IDEXCLUSOREGISTRO IS NULL AND DATAEXCLUSOREGISTRO IS NULL);
    IF presosExistentes = 0 THEN
		UPDATE entradas SET IDEXCLUSOREGISTRO = NEW.IDEXCLUSOREGISTRO, IPEXCLUSOREGISTRO = NEW.IPEXCLUSOREGISTRO WHERE ID = OLD.IDENTRADA;
    END IF;
 END $
