DROP TRIGGER IF EXISTS entradas_INSERT_BEFORE;

delimiter $
CREATE TRIGGER entradas_INSERT_BEFORE
BEFORE INSERT ON entradas
FOR EACH ROW

begin
    IF NEW.DATAENTRADA IS NULL OR NEW.DATAENTRADA = '' OR NEW.DATAENTRADA = '0000-00-00 00:00:00' THEN
		SET NEW.DATAENTRADA = CURRENT_TIMESTAMP;
	END IF;
	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
 END $
DESC entradas;