DROP TRIGGER IF EXISTS entradas_presos_log_INSERT_BEFORE;

delimiter $
CREATE TRIGGER entradas_presos_log_INSERT_BEFORE
BEFORE INSERT ON entradas_presos_log
FOR EACH ROW

begin
	IF NEW.ANTIGO IS NULL OR NEW.ANTIGO = '' THEN
		SET NEW.ANTIGO = '**VAZIO**';
	END IF;
	IF NEW.NOVO IS NULL OR NEW.NOVO = '' THEN
		SET NEW.NOVO = '**VAZIO**';
	END IF;
 END $