DROP TRIGGER IF EXISTS entradas_presos_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER entradas_presos_UPDATE_BEFORE
BEFORE UPDATE ON entradas_presos
FOR EACH ROW

begin
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;
	IF NEW.MATRICULA IS NULL OR NEW.MATRICULA = ''  OR NEW.MATRICULA = '0' THEN
		SET NEW.MATRICULA = NULL;
	END IF;
    IF NEW.RG IS NULL OR NEW.RG = ''THEN
		SET NEW.RG = NULL;
	END IF;
    IF NEW.INFORMACOES IS NULL OR NEW.INFORMACOES = '' THEN
		SET NEW.INFORMACOES = NULL;
	END IF;
    IF NEW.OBSERVACOES IS NULL OR NEW.OBSERVACOES = '' THEN
		SET NEW.OBSERVACOES = NULL;
	END IF;
    IF NEW.DATAPRISAO IS NULL OR NEW.DATAPRISAO = '' THEN
		SET NEW.DATAPRISAO = NULL;
	END IF;
    IF NEW.IDTIPOMOV IS NULL OR NEW.IDTIPOMOV = 0 THEN
		SET NEW.IDTIPOMOV = NULL;
	END IF;
    IF NEW.IDMOTIVOMOV IS NULL OR NEW.IDMOTIVOMOV = 0 THEN
		SET NEW.IDMOTIVOMOV = NULL;
	END IF;
    
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;

	-- Salva os log de alterações
    -- MATRICULA
    IF NEW.MATRICULA IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.MATRICULA; END IF;
    IF OLD.MATRICULA IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.MATRICULA; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO entradas_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'MATRICULA', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- MATRICULAVINCULADA
    IF NEW.MATRICULAVINCULADA IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.MATRICULAVINCULADA; END IF;
    IF OLD.MATRICULAVINCULADA IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.MATRICULAVINCULADA; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO entradas_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'MATRICULAVINCULADA', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- NOME
    IF NEW.NOME IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.NOME; END IF;
    IF OLD.NOME IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.NOME; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO entradas_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'NOME', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- RG
    IF NEW.RG IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.RG; END IF;
    IF OLD.RG IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.RG; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO entradas_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'RG', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- INFORMACOES
    IF NEW.INFORMACOES IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.INFORMACOES; END IF;
    IF OLD.INFORMACOES IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.INFORMACOES; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO entradas_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'INFORMACOES', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- OBSERVACOES
    IF NEW.OBSERVACOES IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.OBSERVACOES; END IF;
    IF OLD.OBSERVACOES IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.OBSERVACOES; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO entradas_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'OBSERVACOES', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- DATAPRISAO
    IF NEW.DATAPRISAO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DATAPRISAO; END IF;
    IF OLD.DATAPRISAO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DATAPRISAO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO entradas_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DATAPRISAO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDTIPOMOV
    IF NEW.IDTIPOMOV IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDTIPOMOV; END IF;
    IF OLD.IDTIPOMOV IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDTIPOMOV; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO entradas_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDTIPOMOV', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDMOTIVOMOV
    IF NEW.IDMOTIVOMOV IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDMOTIVOMOV; END IF;
    IF OLD.IDMOTIVOMOV IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDMOTIVOMOV; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO entradas_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDMOTIVOMOV', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- LANCADOCIMIC
    IF NEW.LANCADOCIMIC IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.LANCADOCIMIC; END IF;
    IF OLD.LANCADOCIMIC IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.LANCADOCIMIC; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO entradas_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'LANCADOCIMIC', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
        
        SET NEW.PROVISORIO = FALSE;
        #INSERE COMO REALIZADO O RECEBIMENTO PENDENTE DO PRESO ORIUNDO DA INCLUSÃO POR TRÂNSITO
        UPDATE cimic_recebimentos SET REALIZADO = TRUE WHERE IDPRESO = OLD.ID;
    END IF;
    
    -- SEGURO
    IF NEW.SEGURO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.SEGURO; END IF;
    IF OLD.SEGURO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.SEGURO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO entradas_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'SEGURO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    SET NEW.DATAATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.IDATUALIZACAO = NULL;
 END $
