DROP TRIGGER IF EXISTS entradas_presos_INSERT_AFTER;

delimiter $
CREATE TRIGGER entradas_presos_INSERT_AFTER
AFTER INSERT ON entradas_presos
FOR EACH ROW

begin    
 	INSERT INTO inc_pertences (IDPRESO, IDTIPOPERTENCE, DATACADASTRO, IDCADASTRO, IPCADASTRO)
 	VALUES(NEW.ID, 1, NEW.DATACADASTRO, NEW.IDCADASTRO, NEW.IPCADASTRO);
	
    INSERT INTO cadastros_condenacao (IDPRESO, DATACADASTRO, IDCADASTRO, IPCADASTRO)
 	VALUES(NEW.ID, NEW.DATACADASTRO, NEW.IDCADASTRO, NEW.IPCADASTRO);
	
 END; $
 