DROP TRIGGER IF EXISTS entradas_artigos_INSERT_BEFORE;

delimiter $
CREATE TRIGGER entradas_artigos_INSERT_BEFORE
BEFORE INSERT ON entradas_artigos
FOR EACH ROW

begin
    IF NEW.OBSERVACOES IS NULL OR NEW.OBSERVACOES = '' THEN
		SET NEW.OBSERVACOES = DEFAULT;
	END IF;
	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;

 END $