DROP TRIGGER IF EXISTS cadastros_movimentacoes_INSERT_BEFORE;

delimiter $
CREATE TRIGGER cadastros_movimentacoes_INSERT_BEFORE
BEFORE INSERT ON cadastros_movimentacoes
FOR EACH ROW

begin
    IF NEW.OBSERVACOES IS NULL OR NEW.OBSERVACOES = '' THEN
		SET NEW.OBSERVACOES = DEFAULT;
	END IF;
	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
 END $
DESC cadastros_movimentacoes;