DROP TRIGGER IF EXISTS funcionarios_escalaplantao_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER funcionarios_escalaplantao_UPDATE_BEFORE
BEFORE UPDATE ON funcionarios_escalaplantao
FOR EACH ROW

BEGIN
	/* DECLARE valorAntigo blob;
	DECLARE valorNovo blob;
    
	IF NEW.RSDATARECEB IS NULL OR NEW.RSDATARECEB = ''  OR NEW.RSDATARECEB = '0' THEN
		SET NEW.RSDATARECEB = NULL;
	END IF;
        
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF; */
    
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;

	/* -- Salva os log de alterações
    -- DATARECEB
    IF NEW.DATARECEB IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DATARECEB; END IF;
    IF OLD.DATARECEB IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DATARECEB; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO funcionarios_escalaplantao_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DATARECEB', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- SEGURO
    IF NEW.SEGURO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.SEGURO; END IF;
    IF OLD.SEGURO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.SEGURO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO funcionarios_escalaplantao_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'SEGURO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    SET NEW.DATAATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.IDATUALIZACAO = NULL;*/
 END; $

DESC funcionarios_escalaplantao;