DROP TRIGGER IF EXISTS funcionarios_escalaplantao_func_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER funcionarios_escalaplantao_func_UPDATE_BEFORE
BEFORE UPDATE ON funcionarios_escalaplantao_func
FOR EACH ROW

BEGIN
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;
    
	IF NEW.OBSERVACOES IS NULL OR NEW.OBSERVACOES = '' THEN
		SET NEW.OBSERVACOES = NULL;
	END IF;
        
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;

	-- Salva os log de alterações
    -- OBSERVACOES
    IF NEW.OBSERVACOES IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.OBSERVACOES; END IF;
    IF OLD.OBSERVACOES IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.OBSERVACOES; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO funcionarios_escalaplantao_func_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'OBSERVACOES', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
        
    -- IDPOSTO
    IF NEW.IDPOSTO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDPOSTO; END IF;
    IF OLD.IDPOSTO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDPOSTO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO funcionarios_escalaplantao_func_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDPOSTO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    #SE O ANTIGO POSTO É O TROCA DE PLANTÃO, ENTÃO SE EXCLUI A TROCA DE PLANTÃO EXISTENTE
    IF NEW.IDPOSTO <> OLD.IDPOSTO AND (SELECT IDTROCA FROM funcionarios_escalapostos WHERE ID = OLD.IDPOSTO) = TRUE THEN
		UPDATE funcionarios_escalaplantao_troca SET IDEXCLUSOREGISTRO = NEW.IDATUALIZACAO, IPEXCLUSOREGISTRO = NEW.IPATUALIZACAO WHERE IDFUNC = OLD.ID AND IDEXCLUSOREGISTRO IS NULL;
    END IF;
	
    SET NEW.DATAATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.IDATUALIZACAO = NULL;
 END; $

DESC funcionarios_escalaplantao_func;