DROP TRIGGER IF EXISTS funcionarios_escalatipo_INSERT_AFTER;

delimiter $
CREATE TRIGGER funcionarios_escalatipo_INSERT_AFTER
AFTER INSERT ON funcionarios_escalatipo
FOR EACH ROW

BEGIN
	#INSERIR O POSTO TROCA DE PLANTÃO COMO PADRÃO
    INSERT INTO funcionarios_escalapostos (NOME, IDTURNO, IDTIPO, ORDEM, COMASSINATURA, ENUMERAR, IDTROCA, IDCADASTRO, IPCADASTRO)
    SELECT 'TROCA DE PLANTÃO',ID,NEW.ID,1,0,0,1,2,'172.14.239.101' FROM tab_turnos WHERE ID < 5 ORDER BY ID;
 END $
DESC funcionarios_escalatipo;