DROP FUNCTION IF EXISTS FUNCT_dados_cela_excecao;
DELIMITER $$
CREATE FUNCTION FUNCT_dados_cela_excecao(intIDMudanca INT)
RETURNS VARCHAR(255)
DETERMINISTIC
BEGIN
	DECLARE intIDMudancaAnterior INT;
	DECLARE intIDMudancaFinal INT;
	DECLARE intIDRAIOORIGEM INT;
	DECLARE intCELAORIGEM INT;
	DECLARE dateDATAORIGEM DATETIME;
	DECLARE intIDRAIODESTINO INT;
	DECLARE intCELADESTINO INT;
	DECLARE dateDATADESTINO DATETIME;
	/*DECLARE intIDRAIOFINAL INT DEFAULT NULL;
	DECLARE intCELADFINAL INT DEFAULT NULL;
	DECLARE dateDATAFINAL DATETIME DEFAULT NULL;*/
	DECLARE intRetorno INT;
    
    SET intIDMudancaAnterior = (SELECT CMUD.ID FROM cadastros_mudancacela CMUD WHERE CMUD.IDPRESO = (SELECT CMUD2.IDPRESO FROM cadastros_mudancacela CMUD2 WHERE CMUD2.ID = intIDMudanca) AND CMUD.ID < intIDMudanca AND CMUD.IDEXCLUSOREGISTRO IS NULL ORDER BY CMUD.ID DESC LIMIT 1);
    
    #SET intIDMudancaFinal = (SELECT CMUD.ID FROM cadastros_mudancacela CMUD WHERE CMUD.IDPRESO = (SELECT CMUD2.IDPRESO FROM cadastros_mudancacela CMUD2 WHERE CMUD2.ID = intIDMudanca) AND CMUD.ID > intIDMudanca AND CMUD.IDEXCLUSOREGISTRO IS NULL ORDER BY CMUD.ID DESC LIMIT 1);
    
    SET intIDRAIOORIGEM = (SELECT RAIO FROM cadastros_mudancacela WHERE ID = intIDMudancaAnterior);
    SET intCELAORIGEM = (SELECT CELA FROM cadastros_mudancacela WHERE ID = intIDMudancaAnterior);
    SET dateDATAORIGEM = (SELECT DATACADASTRO FROM cadastros_mudancacela WHERE ID = intIDMudancaAnterior);
    
    #BUSCA OS DADOS DA CELA ATUAL PARA VER SE É CELA DE EXCEÇÃO DE TRABALHO
    SET intIDRAIODESTINO = (SELECT RAIO FROM cadastros_mudancacela WHERE ID = intIDMudanca);
    SET intCELADESTINO = (SELECT CELA FROM cadastros_mudancacela WHERE ID = intIDMudanca);
    SET dateDATADESTINO = (SELECT DATACADASTRO FROM cadastros_mudancacela WHERE ID = intIDMudanca);
	
    /*#SE NÃO HAVER MAIS REGISTRO DE MUDANÇAS ENTÃO É VERIFICADO SE A ULTIMA CELA FOI PREENCHIDA, PARA DAR ENCERRAMENTO AO PERIODO DE TRABALHO
    IF intIDMudancaFinal IS NULL THEN
		SET intIDRAIOFINAL = (SELECT RAIOALTERADO FROM cadastros_mudancacela WHERE ID = intIDMudanca);
		SET intCELADFINAL = (SELECT CELAALTERADO FROM cadastros_mudancacela WHERE ID = intIDMudanca);
		SET dateDATAFINAL = (SELECT DATAATUALIZACAO FROM cadastros_mudancacela WHERE ID = intIDMudanca);
	END IF;*/
    
    SET intRetorno = (SELECT count(*) FROM tab_raioscelasexcecoes WHERE IDTIPO IN (SELECT ID FROM tab_raioscelasexcecoestipo WHERE CELAREMISSAO = TRUE) AND
    ((IDRAIO = intIDRAIOORIGEM AND CELA = intCELAORIGEM AND DATAINICIO <= dateDATAORIGEM AND (DATATERMINO >= dateDATAORIGEM OR DATATERMINO IS NULL)) OR 
    (IDRAIO = intIDRAIODESTINO AND CELA = intCELADESTINO AND DATAINICIO <= dateDATADESTINO AND (DATATERMINO >= dateDATADESTINO OR DATATERMINO IS NULL)) /*OR 
    (IDRAIO = intIDRAIOFINAL AND CELA = intCELADFINAL AND DATAINICIO <= dateDATAFINAL AND (DATATERMINO >= dateDATAFINAL OR DATATERMINO IS NULL))*/));
    
    return intRetorno;
END; $$
