DROP TRIGGER IF EXISTS inc_pertences_INSERT_BEFORE;

delimiter $
CREATE TRIGGER inc_pertences_INSERT_BEFORE
BEFORE INSERT ON inc_pertences
FOR EACH ROW

BEGIN
	IF NEW.OBSERVACOES IS NULL OR NEW.OBSERVACOES = '' THEN
		SET NEW.OBSERVACOES = NULL;
	END IF;
    
	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
    
	IF NEW.DATAENTRADA IS NULL OR NEW.DATAENTRADA = '' OR NEW.DATAENTRADA = '0000-00-00 00:00:00' THEN
		SET NEW.DATAENTRADA = NEW.DATACADASTRO;
	END IF;
 END; $
DESC inc_pertences;