DROP TRIGGER IF EXISTS inc_kititensentregue_INSERT_BEFORE;

delimiter $
CREATE TRIGGER inc_kititensentregue_INSERT_BEFORE
BEFORE INSERT ON inc_kititensentregue
FOR EACH ROW

begin
	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
 
 END $
