DROP TRIGGER IF EXISTS inc_kititensentregue_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER inc_kititensentregue_UPDATE_BEFORE
BEFORE UPDATE ON inc_kititensentregue
FOR EACH ROW

begin
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;

	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;

    -- QTD
    IF NEW.QTD IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.QTD; END IF;
    IF OLD.QTD IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.QTD; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO inc_kititensentregue_log (IDITEM, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'QTD', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;

	SET NEW.IDATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.DATAATUALIZACAO = NULL;
 END; $
DESC inc_kititensentregue;