DROP TRIGGER IF EXISTS inc_kitentregue_INSERT_AFTER;

delimiter $
CREATE TRIGGER inc_kitentregue_INSERT_AFTER
AFTER INSERT ON inc_kitentregue
FOR EACH ROW

begin
	IF NEW.IDTIPOENTREGA = 1 THEN
		INSERT INTO inc_kititensentregue (IDKIT, IDITEM, QTD, IDCADASTRO, IPCADASTRO)
		SELECT NEW.ID, ID, QTD, NEW.IDCADASTRO, NEW.IPCADASTRO FROM inc_kititens WHERE PADRAOENTREGA = TRUE AND IDEXCLUSOREGISTRO IS NULL;
    END IF;
	
 END; $
 
 DESC inc_kititensentregue;