DROP TRIGGER IF EXISTS inc_kititens_INSERT_BEFORE;

delimiter $
CREATE TRIGGER inc_kititens_INSERT_BEFORE
BEFORE INSERT ON inc_kititens
FOR EACH ROW

begin
	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
    
 	IF NEW.QTD IS NULL OR NEW.QTD = '' OR NEW.QTD = 0 THEN
		SET NEW.QTD = DEFAULT;
	END IF;

 END $
