DROP TRIGGER IF EXISTS inc_kititens_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER inc_kititens_UPDATE_BEFORE
BEFORE UPDATE ON inc_kititens
FOR EACH ROW

begin
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;

	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
	IF NEW.QTD IS NULL OR NEW.QTD = '' OR NEW.QTD = 0 THEN
		SET NEW.QTD = null;
	END IF;

    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;

	-- Salva os log de alterações
    -- NOME
    IF NEW.NOME IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.NOME; END IF;
    IF OLD.NOME IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.NOME; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO inc_kititens_log (IDITEM, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'NOME', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- QTD
    IF NEW.QTD IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.QTD; END IF;
    IF OLD.QTD IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.QTD; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO inc_kititens_log (IDITEM, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'QTD', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- PADRAOENTREGA
    IF NEW.PADRAOENTREGA IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.PADRAOENTREGA; END IF;
    IF OLD.PADRAOENTREGA IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.PADRAOENTREGA; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO inc_kititens_log (IDITEM, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'PADRAOENTREGA', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- MINIMOESTOQUE
    IF NEW.MINIMOESTOQUE IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.MINIMOESTOQUE; END IF;
    IF OLD.MINIMOESTOQUE IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.MINIMOESTOQUE; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO inc_kititens_log (IDITEM, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'MINIMOESTOQUE', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    SET NEW.DATAATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.IDATUALIZACAO = NULL;
 END $
DESC inc_kititens;