DROP TRIGGER IF EXISTS inc_kitentregue_INSERT_BEFORE;

delimiter $
CREATE TRIGGER inc_kitentregue_INSERT_BEFORE
BEFORE INSERT ON inc_kitentregue
FOR EACH ROW

begin
	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
    
	IF NEW.DATAENTREGA IS NULL OR NEW.DATAENTREGA = '' OR NEW.DATAENTREGA = '0000-00-00 00:00:00' THEN
		IF NEW.IDTIPOENTREGA = 1 THEN
			SET NEW.DATAENTREGA = (SELECT E.DATAENTRADA FROM entradas_presos EP INNER JOIN entradas E ON E.ID = EP.IDENTRADA WHERE EP.ID = NEW.IDPRESO);
		ELSE
			SET NEW.DATAENTREGA = CURRENT_TIMESTAMP;
		END IF;
	END IF;
 END; $
