DROP TRIGGER IF EXISTS inc_pertences_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER inc_pertences_UPDATE_BEFORE
BEFORE UPDATE ON inc_pertences
FOR EACH ROW

BEGIN
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;
	IF NEW.OBSERVACOES IS NULL OR NEW.OBSERVACOES = '' THEN
		SET NEW.OBSERVACOES = NULL;
	END IF;
    
	IF NEW.DATAENTRADA IS NULL OR NEW.DATAENTRADA = '' THEN
		SET NEW.DATAENTRADA = OLD.DATACADASTRO;
    END IF;
        
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
	IF NEW.DESCARTADO = TRUE THEN
		SET NEW.NOMERETIRADA = NULL;
		SET NEW.IDGRAUPARENTESCO = NULL;
		SET NEW.DATARETIRADA = NULL;
		SET NEW.IDDESCARTADO = NEW.IDATUALIZACAO;
		SET NEW.IPDESCARTADO = NEW.IPATUALIZACAO;
		IF NEW.DATADESCARTADO IS NULL OR NEW.DATADESCARTADO = '' THEN
			SET NEW.DATADESCARTADO = CURRENT_TIMESTAMP;
		END IF;
	ELSE
    	IF NEW.NOMERETIRADA IS NULL OR NEW.NOMERETIRADA = '' THEN
			SET NEW.NOMERETIRADA = NULL;
		END IF;
		IF NEW.IDGRAUPARENTESCO IS NULL OR NEW.IDGRAUPARENTESCO = '' OR NEW.IDGRAUPARENTESCO = 0 THEN
			SET NEW.IDGRAUPARENTESCO = NULL;
		END IF;
		IF NEW.DATARETIRADA IS NULL OR NEW.DATARETIRADA = '' OR NEW.DATARETIRADA = '0000-00-00 00:00:00' THEN
			SET NEW.DATARETIRADA = NULL;
		END IF;
		SET NEW.IDDESCARTADO = NULL;
		SET NEW.IPDESCARTADO = NULL;
		SET NEW.DATADESCARTADO = NULL;
	END IF;
    
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;

	-- Salva os log de alterações
    -- DATAENTRADA
    IF NEW.DATAENTRADA IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DATAENTRADA; END IF;
    IF OLD.DATAENTRADA IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DATAENTRADA; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO inc_pertences_log (IDPERTENCE, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DATAENTRADA', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- NOMERETIRADA
    IF NEW.NOMERETIRADA IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.NOMERETIRADA; END IF;
    IF OLD.NOMERETIRADA IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.NOMERETIRADA; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO inc_pertences_log (IDPERTENCE, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'NOMERETIRADA', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDGRAUPARENTESCO
    IF NEW.IDGRAUPARENTESCO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDGRAUPARENTESCO; END IF;
    IF OLD.IDGRAUPARENTESCO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDGRAUPARENTESCO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO inc_pertences_log (IDPERTENCE, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDGRAUPARENTESCO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- DATARETIRADA
    IF NEW.DATARETIRADA IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DATARETIRADA; END IF;
    IF OLD.DATARETIRADA IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DATARETIRADA; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO inc_pertences_log (IDPERTENCE, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DATARETIRADA', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- OBSERVACOES
    IF NEW.OBSERVACOES IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.OBSERVACOES; END IF;
    IF OLD.OBSERVACOES IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.OBSERVACOES; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO inc_pertences_log (IDPERTENCE, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'OBSERVACOES', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;

    -- DESCARTADO
    IF NEW.DESCARTADO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DESCARTADO; END IF;
    IF OLD.DESCARTADO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DESCARTADO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO inc_pertences_log (IDPERTENCE, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DESCARTADO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;

    -- DATADESCARTADO
    IF NEW.DATADESCARTADO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DATADESCARTADO; END IF;
    IF OLD.DATADESCARTADO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DATADESCARTADO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO inc_pertences_log (IDPERTENCE, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DATADESCARTADO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;

    SET NEW.DATAATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.IDATUALIZACAO = NULL;
 END; $
DESC inc_pertences;

