DROP PROCEDURE IF EXISTS PROCED_verifica_retorna_numero_oficio_unidade_intermediaria;
DELIMITER $$
CREATE PROCEDURE PROCED_verifica_retorna_numero_oficio_unidade_intermediaria(IN intIDMOVIMENTACAOORDEM INT, IN intIDDESTINO INT,IN intANO INT, IN intTIPOOFICIO INT, IN intIDCADASTRO INT, IN chrIPCADASTRO varchar(20), OUT intID INT)
BEGIN
	DECLARE intUltimo INT;
    DECLARE intOFICIOEXISTENTE INT;
    
    SET intOFICIOEXISTENTE = (
		SELECT CMEI.IDOFICIOINTERM FROM cimic_transferencias_intermed CMEI
        INNER JOIN cimic_transferencias CT ON CT.ID = CMEI.IDMOVIMENTACAO
        WHERE CMEI.IDDESTINOINTERM = intIDDESTINO AND CT.IDORDEMSAIDAMOV = intIDMOVIMENTACAOORDEM
        AND CMEI.IDEXCLUSOREGISTRO IS NULL AND CMEI.DATAEXCLUSOREGISTRO IS NULL LIMIT 1
        );
    
    IF intOFICIOEXISTENTE IS NULL THEN
		CALL PROCED_gera_numero_oficio(intANO, intTIPOOFICIO, intIDCADASTRO, chrIPCADASTRO, @intIDOFICIO);
		SET intID = @intIDOFICIO;
		SET @intIDOFICIO = 0;
	ELSE
		SET intID = intOFICIOEXISTENTE;
	END IF;
    
END; $$

