DROP TRIGGER IF EXISTS rol_visitantes_INSERT_BEFORE;

delimiter $
CREATE TRIGGER rol_visitantes_INSERT_BEFORE
BEFORE INSERT ON rol_visitantes
FOR EACH ROW

begin
	
 	IF NEW.COMENTARIO IS NULL OR NEW.COMENTARIO = '' THEN
 		SET NEW.COMENTARIO = DEFAULT;
 	END IF;
	
 	IF NEW.OBSERVACOES IS NULL OR NEW.OBSERVACOES = '' THEN
 		SET NEW.OBSERVACOES = DEFAULT;
 	END IF;
	
    -- O ID SITUAÇÃO SÓ PODE ESTAR ENTRE OS PERMITIDOS
 	IF NEW.IDSITUACAO IS NULL OR NEW.IDSITUACAO = 0 OR NEW.IDSITUACAO NOT IN (SELECT IDSITUACAO FROM tab_situacaofiltro WHERE IDTIPO = 9)THEN
 		SET NEW.IDSITUACAO = DEFAULT;
 	END IF;
	
 	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
 		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
 	END IF;
     
END; $

DESC rol_visitantes;