
DROP TRIGGER IF EXISTS rol_visitantes_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER rol_visitantes_UPDATE_BEFORE
BEFORE UPDATE ON rol_visitantes
FOR EACH ROW

begin
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;
	
 	IF NEW.CPF IS NULL OR NEW.CPF = '' THEN
 		SET NEW.CPF = DEFAULT;
 	END IF;
    
 	IF NEW.COMENTARIO IS NULL OR NEW.COMENTARIO = '' THEN
 		SET NEW.COMENTARIO = DEFAULT;
 	END IF;
    
 	IF NEW.NOMESOCIAL IS NULL OR NEW.NOMESOCIAL = '' THEN
 		SET NEW.NOMESOCIAL = DEFAULT;
 	END IF;
    
    IF NEW.OBSERVACOES IS NULL OR NEW.OBSERVACOES = '' THEN
		SET NEW.OBSERVACOES = DEFAULT;
	END IF;
    
    IF NEW.BAIRRO IS NULL OR NEW.BAIRRO = '' THEN
		SET NEW.BAIRRO = DEFAULT;
	END IF;

    IF NEW.COMPLEMENTO IS NULL OR NEW.COMPLEMENTO = '' THEN
		SET NEW.COMPLEMENTO = DEFAULT;
	END IF;

	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;
    
	-- Salva os log de alterações
    -- NOME
    IF NEW.NOME IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.NOME; END IF;
    IF OLD.NOME IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.NOME; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'NOME', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- NOMESOCIAL
    IF NEW.NOMESOCIAL IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.NOMESOCIAL; END IF;
    IF OLD.NOMESOCIAL IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.NOMESOCIAL; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'NOMESOCIAL', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- RG
    IF NEW.RG IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.RG; END IF;
    IF OLD.RG IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.RG; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'RG', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDEMISSORRG
    IF NEW.IDEMISSORRG IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDEMISSORRG; END IF;
    IF OLD.IDEMISSORRG IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDEMISSORRG; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDEMISSORRG', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDESTADORG
    IF NEW.IDESTADORG IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDESTADORG; END IF;
    IF OLD.IDESTADORG IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDESTADORG; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDESTADORG', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- CPF
    IF NEW.CPF IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.CPF; END IF;
    IF OLD.CPF IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.CPF; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'CPF', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- PAI
    IF NEW.PAI IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.PAI; END IF;
    IF OLD.PAI IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.PAI; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'PAI', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- MAE
    IF NEW.MAE IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.MAE; END IF;
    IF OLD.MAE IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.MAE; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'MAE', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- OBSERVACOES
    IF NEW.OBSERVACOES IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.OBSERVACOES; END IF;
    IF OLD.OBSERVACOES IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.OBSERVACOES; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'OBSERVACOES', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDNACIONALIDADE
    IF NEW.IDNACIONALIDADE IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDNACIONALIDADE; END IF;
    IF OLD.IDNACIONALIDADE IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDNACIONALIDADE; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDNACIONALIDADE', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDCIDADENASC
    IF NEW.IDCIDADENASC IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDCIDADENASC; END IF;
    IF OLD.IDCIDADENASC IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDCIDADENASC; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDCIDADENASC', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- DATANASC
    IF NEW.DATANASC IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DATANASC; END IF;
    IF OLD.DATANASC IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DATANASC; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DATANASC', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- EMANCIPADO
    IF NEW.EMANCIPADO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.EMANCIPADO; END IF;
    IF OLD.EMANCIPADO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.EMANCIPADO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'EMANCIPADO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- ENDERECO
    IF NEW.ENDERECO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.ENDERECO; END IF;
    IF OLD.ENDERECO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.ENDERECO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'ENDERECO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- NUMERO
    IF NEW.NUMERO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.NUMERO; END IF;
    IF OLD.NUMERO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.NUMERO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'NUMERO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- BAIRRO
    IF NEW.BAIRRO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.BAIRRO; END IF;
    IF OLD.BAIRRO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.BAIRRO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'BAIRRO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- COMPLEMENTO
    IF NEW.COMPLEMENTO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.COMPLEMENTO; END IF;
    IF OLD.COMPLEMENTO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.COMPLEMENTO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'COMPLEMENTO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDCIDADEMORADIA
    IF NEW.IDCIDADEMORADIA IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDCIDADEMORADIA; END IF;
    IF OLD.IDCIDADEMORADIA IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDCIDADEMORADIA; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDCIDADEMORADIA', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    IF NEW.IDEXCLUSOREGISTRO IS NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		-- IDSITUACAO
		-- O ID SITUAÇÃO SÓ PODE ESTAR ENTRE O ARRAY DESSE TIPO
		IF (NEW.IDSITUACAO <> OLD.IDSITUACAO AND NEW.IDSITUACAO IN (SELECT IDSITUACAO FROM tab_situacaofiltro WHERE IDTIPO = 9))
        OR (NEW.IDSITUACAO = OLD.IDSITUACAO AND NEW.COMENTARIO <> OLD.COMENTARIO) THEN
			-- Insere a alteração da situação
			INSERT INTO rol_visitantessituacao (IDREFERENCIA, IDSITUACAO, COMENTARIO, IDCADASTRO, IPCADASTRO, DATACADASTRO) VALUES 
			(OLD.ID, NEW.IDSITUACAO, NEW.COMENTARIO, NEW.IDATUALIZACAO, NEW.IPATUALIZACAO, NEW.DATAATUALIZACAO);
		ELSE
			SET NEW.IDSITUACAO = OLD.IDSITUACAO;
		END IF;
	ELSE
		SET NEW.IDSITUACAO = OLD.IDSITUACAO;
		SET NEW.COMENTARIO = OLD.COMENTARIO;
	END IF;
	    
	SET NEW.DATAATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.IDATUALIZACAO = NULL;
 END $

DESC rol_visitantes;
