
DROP TRIGGER IF EXISTS rol_visitantes_presos_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER rol_visitantes_presos_UPDATE_BEFORE
BEFORE UPDATE ON rol_visitantes_presos
FOR EACH ROW

begin
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;
	
    IF NEW.COMENTARIO IS NULL OR NEW.COMENTARIO = '' THEN
		SET NEW.COMENTARIO = DEFAULT;
	END IF;
    
    IF NEW.IDRESPONSAVEL IS NULL OR NEW.IDRESPONSAVEL = 0 THEN
		SET NEW.IDRESPONSAVEL = DEFAULT;
	END IF;
    
    IF NEW.IDPARENTRESP IS NULL OR NEW.IDPARENTRESP = 0 THEN
		SET NEW.IDPARENTRESP = DEFAULT;
	END IF;
    
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;
    
	-- Salva os log de alterações
    -- IDVISITANTE
    IF NEW.IDVISITANTE IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDVISITANTE; END IF;
    IF OLD.IDVISITANTE IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDVISITANTE; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDVISITANTE', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDPARENTESCO
    IF NEW.IDPARENTESCO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDPARENTESCO; END IF;
    IF OLD.IDPARENTESCO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDPARENTESCO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDPARENTESCO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDRESPONSAVEL
    IF NEW.IDRESPONSAVEL IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDRESPONSAVEL; END IF;
    IF OLD.IDRESPONSAVEL IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDRESPONSAVEL; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDRESPONSAVEL', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDPARENTRESP
    IF NEW.IDPARENTRESP IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDPARENTRESP; END IF;
    IF OLD.IDPARENTRESP IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDPARENTRESP; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO rol_visitantes_presos_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDPARENTRESP', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    IF NEW.IDEXCLUSOREGISTRO IS NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		-- IDSITUACAO
		-- O ID SITUAÇÃO SÓ PODE ESTAR ENTRE O ARRAY DESSE TIPO
		IF (NEW.IDSITUACAO <> OLD.IDSITUACAO AND NEW.IDSITUACAO IN (SELECT IDSITUACAO FROM tab_situacaofiltro WHERE IDTIPO = 10))
        OR (NEW.IDSITUACAO = OLD.IDSITUACAO AND NEW.COMENTARIO <> OLD.COMENTARIO) THEN
			-- Insere a alteração da situação
			INSERT INTO rol_visitantes_presossituacao (IDREFERENCIA, IDSITUACAO, COMENTARIO, IDCADASTRO, IPCADASTRO, DATACADASTRO) VALUES 
			(OLD.ID, NEW.IDSITUACAO, NEW.COMENTARIO, NEW.IDATUALIZACAO, NEW.IPATUALIZACAO, NEW.DATAATUALIZACAO);
		ELSE
			SET NEW.IDSITUACAO = OLD.IDSITUACAO;
		END IF;
	ELSE
		SET NEW.IDSITUACAO = OLD.IDSITUACAO;
		SET NEW.COMENTARIO = OLD.COMENTARIO;
	END IF;
	    
	SET NEW.DATAATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.IDATUALIZACAO = NULL;
 END $

DESC rol_visitantes_presos;
