DROP TRIGGER IF EXISTS rol_movimentacoes_INSERT_BEFORE;

delimiter $
CREATE TRIGGER rol_movimentacoes_INSERT_BEFORE
BEFORE INSERT ON rol_movimentacoes
FOR EACH ROW

BEGIN
	IF NEW.DATAENTRADA IS NULL OR NEW.DATAENTRADA = '' OR NEW.DATAENTRADA = '0000-00-00 00:00:00' THEN
		SET NEW.DATAENTRADA = CURRENT_TIMESTAMP;
	END IF;
    
	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
    
 END $
DESC rol_movimentacoes;