DROP TRIGGER IF EXISTS tab_diretorestipos_INSERT_BEFORE;

delimiter $
CREATE TRIGGER tab_diretorestipos_INSERT_BEFORE
BEFORE INSERT ON tab_diretorestipos
FOR EACH ROW

begin
	SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;

END; $
