DROP TRIGGER IF EXISTS tab_unidades_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER tab_unidades_UPDATE_BEFORE
BEFORE UPDATE ON tab_unidades
FOR EACH ROW

BEGIN
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;
	IF NEW.NOMEATRIBUIDO IS NULL OR NEW.NOMEATRIBUIDO = ''  THEN
		SET NEW.NOMEATRIBUIDO = NULL;
	END IF;
    
	IF NEW.DIRETOR IS NULL OR NEW.DIRETOR = ''  THEN
		SET NEW.DIRETOR = NULL;
	END IF;
    
	IF NEW.EMAILNOTES IS NULL OR NEW.EMAILNOTES = ''  THEN
		SET NEW.EMAILNOTES = NULL;
	END IF;
    
	IF NEW.EMAILCIMIC IS NULL OR NEW.EMAILCIMIC = ''  THEN
		SET NEW.EMAILCIMIC = NULL;
	END IF;
    
	IF NEW.ENDERECO IS NULL OR NEW.ENDERECO = ''  THEN
		SET NEW.ENDERECO = NULL;
	END IF;
    
	IF NEW.CEP IS NULL OR NEW.CEP = ''  THEN
		SET NEW.CEP = NULL;
	END IF;
    
	IF NEW.TELEFONES IS NULL OR NEW.TELEFONES = ''  THEN
		SET NEW.TELEFONES = NULL;
	END IF;
    
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;

	-- Salva os log de alterações
    -- IDCIDADE
    IF NEW.IDCIDADE IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDCIDADE; END IF;
    IF OLD.IDCIDADE IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDCIDADE; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_unidades_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDCIDADE', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDPERFIL
    IF NEW.IDPERFIL IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDPERFIL; END IF;
    IF OLD.IDPERFIL IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDPERFIL; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_unidades_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDPERFIL', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- CODIGO
    IF NEW.CODIGO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.CODIGO; END IF;
    IF OLD.CODIGO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.CODIGO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_unidades_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'CODIGO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- NOMEUNIDADE
    IF NEW.NOMEUNIDADE IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.NOMEUNIDADE; END IF;
    IF OLD.NOMEUNIDADE IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.NOMEUNIDADE; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_unidades_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'NOMEUNIDADE', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- NOMEATRIBUIDO
    IF NEW.NOMEATRIBUIDO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.NOMEATRIBUIDO; END IF;
    IF OLD.NOMEATRIBUIDO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.NOMEATRIBUIDO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_unidades_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'NOMEATRIBUIDO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDTIPOUNIDADE
    IF NEW.IDTIPOUNIDADE IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDTIPOUNIDADE; END IF;
    IF OLD.IDTIPOUNIDADE IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDTIPOUNIDADE; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_unidades_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDTIPOUNIDADE', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDCOORDENADORIA
    IF NEW.IDCOORDENADORIA IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDCOORDENADORIA; END IF;
    IF OLD.IDCOORDENADORIA IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDCOORDENADORIA; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_unidades_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDCOORDENADORIA', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- DIRETOR
    IF NEW.DIRETOR IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DIRETOR; END IF;
    IF OLD.DIRETOR IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DIRETOR; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_unidades_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DIRETOR', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- EMAILNOTES
    IF NEW.EMAILNOTES IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.EMAILNOTES; END IF;
    IF OLD.EMAILNOTES IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.EMAILNOTES; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_unidades_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'EMAILNOTES', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- EMAILCIMIC
    IF NEW.EMAILCIMIC IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.EMAILCIMIC; END IF;
    IF OLD.EMAILCIMIC IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.EMAILCIMIC; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_unidades_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'EMAILCIMIC', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- ENDERECO
    IF NEW.ENDERECO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.ENDERECO; END IF;
    IF OLD.ENDERECO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.ENDERECO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_unidades_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'ENDERECO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- CEP
    IF NEW.CEP IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.CEP; END IF;
    IF OLD.CEP IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.CEP; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_unidades_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'CEP', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- TELEFONES
    IF NEW.TELEFONES IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.TELEFONES; END IF;
    IF OLD.TELEFONES IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.TELEFONES; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_unidades_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'TELEFONES', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    SET NEW.DATAATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.IDATUALIZACAO = NULL;
 END; $
 
desc tab_unidades;
