DROP TRIGGER IF EXISTS tab_usuariospermissoes_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER tab_usuariospermissoes_UPDATE_BEFORE
BEFORE UPDATE ON tab_usuariospermissoes
FOR EACH ROW

BEGIN
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;
    
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
	
    /*IF NEW.DATAINICIO <> OLD.DATAINICIO AND NEW.DATAINICIO < OLD.DATATERMINO AND @intUsuario <> OLD.IDUSUARIO THEN
		SET NEW.DATAINICIO = DATE_ADD(NEW.DATAINICIO, INTERVAL 1 DAY);
	END IF;
    
    IF NEW.DATAINICIO = OLD.DATATERMINO AND @intUsuario <> OLD.IDUSUARIO THEN
		SET NEW.IDEXCLUSOREGISTRO = NEW.IDATUALIZACAO;
		SET NEW.IPEXCLUSOREGISTRO = NEW.IPATUALIZACAO;
	END IF;
    
	IF NEW.DATATERMINO <> OLD.DATATERMINO AND NEW.DATATERMINO > OLD.DATAINICIO AND @intUsuario <> OLD.IDUSUARIO THEN
		SET NEW.DATATERMINO = DATE_ADD(NEW.DATATERMINO, INTERVAL -1 DAY);
	END IF;
    
    IF NEW.DATATERMINO = OLD.DATAINICIO AND @intUsuario <> OLD.IDUSUARIO THEN
		SET NEW.IDEXCLUSOREGISTRO = NEW.IDATUALIZACAO;
		SET NEW.IPEXCLUSOREGISTRO = NEW.IPATUALIZACAO;
	END IF;*/
	
	IF NEW.IDEXCLUSOREGISTRO IS NOT NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR  NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = DEFAULT;
		END IF;
        
        IF (SELECT DIRETOR FROM tab_permissoes WHERE ID = OLD.IDPERMISSAO) = 1 THEN
			UPDATE chefia_boletim SET IDDIRETOR = NULL, IDATUALIZACAO = NEW.IDEXCLUSOREGISTRO, IPATUALIZACAO = NEW.IPEXCLUSOREGISTRO WHERE IDDIRETOR = OLD.ID AND BOLETIMDODIA = TRUE;
        END IF;
    END IF;
    
	-- Salva os log de alterações
    -- DATAINICIO
    IF NEW.DATAINICIO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DATAINICIO; END IF;
    IF OLD.DATAINICIO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DATAINICIO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_usuariospermissoes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DATAINICIO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;

    -- DATATERMINO
    IF NEW.DATATERMINO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DATATERMINO; END IF;
    IF OLD.DATATERMINO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DATATERMINO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_usuariospermissoes_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DATATERMINO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;

	SET NEW.IDATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.DATAATUALIZACAO = NULL;
    
END; $
DESC tab_usuariospermissoes;