DROP TRIGGER IF EXISTS tab_usuariospermissoes_INSERT_BEFORE;

delimiter $
CREATE TRIGGER tab_usuariospermissoes_INSERT_BEFORE
before insert ON tab_usuariospermissoes
FOR EACH ROW

begin
	DECLARE blnDiretor BOOL DEFAULT FALSE;
    
    IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
	IF NEW.IPCADASTRO IS NULL OR NEW.IPCADASTRO = '' THEN
		SET NEW.IPCADASTRO = DEFAULT;
    END IF;
    
    IF NEW.IDBOLETIMPERMISSAO = 0 THEN
		SET NEW.IDBOLETIMPERMISSAO = NULL;
	END IF;
    
	IF NEW.DATAINICIO = 0 THEN
		SET NEW.DATAINICIO = NULL;
	END IF;

	IF NEW.DATATERMINO = 0 THEN
		SET NEW.DATATERMINO = NULL;
	END IF;
    
END; $

DESC tab_usuariospermissoes;