DROP TRIGGER IF EXISTS tab_usuarios_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER tab_usuarios_UPDATE_BEFORE
BEFORE UPDATE ON tab_usuarios
FOR EACH ROW

BEGIN
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;
	IF NEW.RSUSUARIO IS NULL OR NEW.RSUSUARIO = ''  OR NEW.RSUSUARIO = '0' THEN
		SET NEW.RSUSUARIO = NULL;
	END IF;
    
	IF NEW.APELIDO IS NULL OR NEW.APELIDO = '' THEN
		SET NEW.APELIDO = DEFAULT;
    END IF;
    
	IF NEW.DATAATUALIZACAO IS NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
    END IF;
    
	IF NEW.SENHA IS NULL OR NEW.SENHA = '' THEN
		SET NEW.SENHA = MD5(123456);
    END IF;
    
	IF NEW.RG IS NULL OR NEW.RG = '' THEN
		SET NEW.RG = DEFAULT;
    END IF;
    
    IF NEW.IDESCALA IS NULL OR NEW.IDESCALA = 0 OR NEW.IDESCALA = '' THEN
		SET NEW.IDESCALA = DEFAULT;
	END IF;

	IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;

	-- Salva os log de alterações
    -- USUARIO
    IF NEW.USUARIO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.USUARIO; END IF;
    IF OLD.USUARIO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.USUARIO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_usuarios_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'USUARIO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- RSUSUARIO
    IF NEW.RSUSUARIO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.RSUSUARIO; END IF;
    IF OLD.RSUSUARIO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.RSUSUARIO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_usuarios_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'RSUSUARIO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- NOME
    IF NEW.NOME IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.NOME; END IF;
    IF OLD.NOME IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.NOME; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_usuarios_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'NOME', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- APELIDO
    IF NEW.APELIDO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.APELIDO; END IF;
    IF OLD.APELIDO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.APELIDO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_usuarios_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'APELIDO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- RG
    IF NEW.RG IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.RG; END IF;
    IF OLD.RG IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.RG; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_usuarios_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'RG', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- CPF
    IF NEW.CPF IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.CPF; END IF;
    IF OLD.CPF IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.CPF; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_usuarios_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'CPF', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    -- IDTURNO
    IF NEW.IDTURNO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.IDTURNO; END IF;
    IF OLD.IDTURNO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.IDTURNO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_usuarios_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'IDTURNO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;
    
    SET NEW.DATAATUALIZACAO = NULL;
	SET NEW.IPATUALIZACAO = NULL;
	SET NEW.IDATUALIZACAO = NULL;
 END; $

DESC tab_usuarios;