DROP TRIGGER IF EXISTS tab_raioscelasexcecoes_INSERT_BEFORE;

delimiter $
CREATE TRIGGER tab_raioscelasexcecoes_INSERT_BEFORE
BEFORE INSERT ON tab_raioscelasexcecoes
FOR EACH ROW

BEGIN
	IF NEW.DATAINICIO IS NULL OR NEW.DATAINICIO = '' OR NEW.DATAINICIO = '0000-00-00 00:00:00' THEN
		SET NEW.DATAINICIO = CURRENT_TIMESTAMP;
	END IF;
    
	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
 END $
DESC tab_raioscelasexcecoes;