DROP TRIGGER IF EXISTS tab_usuarios_INSERT_BEFORE;

delimiter $
CREATE TRIGGER tab_usuarios_INSERT_BEFORE
BEFORE INSERT ON tab_usuarios
FOR EACH ROW

BEGIN
    IF NEW.RSUSUARIO IS NULL OR NEW.RSUSUARIO = 0 THEN
		SET NEW.RSUSUARIO = DEFAULT;
	END IF;
    IF NEW.APELIDO IS NULL OR NEW.APELIDO = '' THEN
		SET NEW.APELIDO = DEFAULT;
	END IF;
    IF NEW.SENHA IS NULL OR NEW.SENHA = '' THEN
		SET NEW.SENHA = MD5(123456);
	END IF;

    IF NEW.IDESCALA IS NULL OR NEW.IDESCALA = 0 OR NEW.IDESCALA = '' THEN
		SET NEW.IDESCALA = NULL;
	END IF;

	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
 END $
DESC tab_usuarios;