DROP TRIGGER IF EXISTS tab_computadores_aute_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER tab_computadores_aute_UPDATE_BEFORE
BEFORE UPDATE ON tab_computadores_aute
FOR EACH ROW

BEGIN
        
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;

 END; $

DESC tab_computadores_aute;