DROP TRIGGER IF EXISTS tab_diretores_temporarios_UPDATE_BEFORE;

delimiter $
CREATE TRIGGER tab_diretores_temporarios_UPDATE_BEFORE
BEFORE UPDATE ON tab_diretores_temporarios
FOR EACH ROW

BEGIN
	DECLARE valorAntigo blob;
	DECLARE valorNovo blob;

	IF NEW.DATAATUALIZACAO IS NOT NULL OR NEW.DATAATUALIZACAO = '' THEN
		SET NEW.DATAATUALIZACAO = CURRENT_TIMESTAMP;
	END IF;
    
    IF NEW.IDEXCLUSOREGISTRO IS NOT NULL AND OLD.IDEXCLUSOREGISTRO IS NULL THEN
		IF NEW.DATAEXCLUSOREGISTRO IS NULL OR NEW.DATAEXCLUSOREGISTRO = '' THEN
			SET NEW.DATAEXCLUSOREGISTRO = CURRENT_TIMESTAMP;
		END IF;
		IF NEW.IPEXCLUSOREGISTRO IS NULL OR NEW.IPEXCLUSOREGISTRO = '' THEN
			SET NEW.IPEXCLUSOREGISTRO = NULL;
		END IF;
	END IF;
    
    -- DATAINICIO
    IF NEW.DATAINICIO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DATAINICIO; END IF;
    IF OLD.DATAINICIO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DATAINICIO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_diretores_temporarios_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DATAINICIO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;

    -- DATATERMINO
    IF NEW.DATATERMINO IS NULL THEN SET valorNovo = '**VAZIO**'; ELSE  SET valorNovo = NEW.DATATERMINO; END IF;
    IF OLD.DATATERMINO IS NULL THEN SET valorAntigo = '**VAZIO**'; ELSE  SET valorAntigo = OLD.DATATERMINO; END IF;
    IF valorAntigo <> valorNovo THEN
		INSERT INTO tab_diretores_temporarios_log (IDREFERENCIA, CAMPOATUALIZADO, ANTIGO, NOVO, IDATUALIZACAO, DATAATUALIZACAO, IPATUALIZACAO)
        VALUES (OLD.ID, 'DATATERMINO', valorAntigo, valorNovo, NEW.IDATUALIZACAO, NEW.DATAATUALIZACAO, NEW.IPATUALIZACAO);
    END IF;

 END; $

DESC tab_diretores_temporarios;
DESC tab_diretores_temporarios_log;