DROP TRIGGER IF EXISTS tab_artigos_INSERT_BEFORE;

delimiter $
CREATE TRIGGER tab_artigos_INSERT_BEFORE
BEFORE INSERT ON tab_artigos
FOR EACH ROW

begin
	IF NEW.DATACADASTRO IS NULL OR NEW.DATACADASTRO = '' OR NEW.DATACADASTRO = '0000-00-00 00:00:00' THEN
		SET NEW.DATACADASTRO = CURRENT_TIMESTAMP;
	END IF;
	IF NEW.IPCADASTRO IS NULL OR NEW.IPCADASTRO = '' THEN
		SET NEW.IPCADASTRO = NULL;
	END IF;
 END $
DESC tab_artigos;