DROP TRIGGER IF EXISTS TRIGGER_INSERT_tab_usuarioshistoricoerrosenha;

delimiter $
CREATE TRIGGER TRIGGER_INSERT_tab_usuarioshistoricoerrosenha
after insert ON tab_usuarioshistoricoerrosenha
FOR EACH ROW

begin
    
    IF (SELECT QTDERROSENHA FROM tab_usuarios WHERE ID = NEW.IDUSUARIO) >= 4 THEN
		INSERT INTO tab_usuarioshistoricobloqueios(IDUSUARIO, IDTIPOBLOQUEIO, HORABLOQUEIO, HORALIBERACAO) VALUES
        (NEW.IDUSUARIO, 1, CURRENT_TIMESTAMP, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 3 HOUR));
   		
        UPDATE tab_usuarios SET QTDERROSENHA = 0 WHERE ID = NEW.IDUSUARIO;

   ELSE
		UPDATE tab_usuarios SET QTDERROSENHA = QTDERROSENHA + 1 WHERE ID = NEW.IDUSUARIO;

	END IF;
    
END; $
