DROP TRIGGER IF EXISTS TRIGGER_UPDATE_tab_usuarioshistoricosolicitacaoredefinirsenha;

delimiter $
CREATE TRIGGER TRIGGER_UPDATE_tab_usuarioshistoricosolicitacaoredefinirsenha
BEFORE UPDATE ON tab_usuarioshistoricosolicitacaoredefinirsenha
FOR EACH ROW

begin
	IF NEW.SOLICITACAOATENDIDA = TRUE THEN
		SET NEW.HORAATENDIDA = CURRENT_TIMESTAMP;
		-- ZERA A QUANTIDADE DE ERROS DE LOGIN E PERGUNTAS DE SEGURANÇA
    	UPDATE tab_usuarios SET SOLICITACAOREDEFINIRSENHA = FALSE, QTDERROSENHA = 0, QTDERROPERGUNTASEGURANCA = 0 
        WHERE ID = NEW.IDUSUARIO;
		-- ZERA OS BLOQUEIOS QUE HOUVER
		UPDATE tab_usuarioshistoricobloqueios SET PRAZOINTERROMPIDO = TRUE 
        WHERE IDUSUARIO = OLD.IDUSUARIO AND TIMESTAMPDIFF(MINUTE,HORALIBERACAO,CURRENT_TIMESTAMP) <= 0;

    END IF;
    
	IF NEW.SOLICITACAOCANCELADA = TRUE THEN
		SET NEW.HORACANCELADA = CURRENT_TIMESTAMP;
		-- UPDATE tab_usuarios SET SOLICITACAOREDEFINIRSENHA = FALSE WHERE ID = NEW.IDUSUARIO;
    END IF;
	
END; $