DROP TRIGGER IF EXISTS TRIGGER_INSERT_tab_usuarioshistoricoerroredefinirsenha;

delimiter $
CREATE TRIGGER TRIGGER_INSERT_tab_usuarioshistoricoerroredefinirsenha
after insert ON tab_usuarioshistoricoerroredefinirsenha
FOR EACH ROW

begin
    
    IF (SELECT QTDERROPERGUNTASEGURANCA FROM tab_usuarios WHERE ID = NEW.IDUSUARIO) >= 4 THEN
		INSERT INTO tab_usuarioshistoricobloqueios(IDUSUARIO, IDTIPOBLOQUEIO, HORABLOQUEIO, HORALIBERACAO) VALUES
        (NEW.IDUSUARIO, 2, CURRENT_TIMESTAMP, DATE_ADD(CURRENT_TIMESTAMP, INTERVAL 3 HOUR));
   		
        UPDATE tab_usuarios SET QTDERROPERGUNTASEGURANCA = 0 WHERE ID = NEW.IDUSUARIO;

   ELSE
		UPDATE tab_usuarios SET QTDERROPERGUNTASEGURANCA = QTDERROPERGUNTASEGURANCA + 1 WHERE ID = NEW.IDUSUARIO;

	END IF;
    
END; $
